/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  GetThermoDataOptimizationOptIdThermoDataGetParams,
  HTTPValidationError,
  ThermoData,
  UpdateThermoDataOptimizationOptIdThermoDataPatchBody
} from '.././model';



  
  
  
/**
 * @summary Get thermo data for optimization
 */
export type getThermoDataOptimizationOptIdThermoDataGetResponse200 = {
  data: ThermoData
  status: 200
}

export type getThermoDataOptimizationOptIdThermoDataGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getThermoDataOptimizationOptIdThermoDataGetResponseSuccess = (getThermoDataOptimizationOptIdThermoDataGetResponse200) & {
  headers: Headers;
};
export type getThermoDataOptimizationOptIdThermoDataGetResponseError = (getThermoDataOptimizationOptIdThermoDataGetResponse422) & {
  headers: Headers;
};

export type getThermoDataOptimizationOptIdThermoDataGetResponse = (getThermoDataOptimizationOptIdThermoDataGetResponseSuccess | getThermoDataOptimizationOptIdThermoDataGetResponseError)

export const getGetThermoDataOptimizationOptIdThermoDataGetUrl = (optId: number,
    params?: GetThermoDataOptimizationOptIdThermoDataGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/optimization/${optId}/thermo_data?${stringifiedParams}` : `/optimization/${optId}/thermo_data`
}

export const getThermoDataOptimizationOptIdThermoDataGet = async (optId: number,
    params?: GetThermoDataOptimizationOptIdThermoDataGetParams, options?: RequestInit): Promise<getThermoDataOptimizationOptIdThermoDataGetResponse> => {
  
  const res = await fetch(getGetThermoDataOptimizationOptIdThermoDataGetUrl(optId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getThermoDataOptimizationOptIdThermoDataGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getThermoDataOptimizationOptIdThermoDataGetResponse
}




export const getGetThermoDataOptimizationOptIdThermoDataGetKey = (optId: number,
    params?: GetThermoDataOptimizationOptIdThermoDataGetParams,) => [`/optimization/${optId}/thermo_data`, ...(params ? [params]: [])] as const;

export type GetThermoDataOptimizationOptIdThermoDataGetQueryResult = NonNullable<Awaited<ReturnType<typeof getThermoDataOptimizationOptIdThermoDataGet>>>
export type GetThermoDataOptimizationOptIdThermoDataGetQueryError = Promise<HTTPValidationError>

/**
 * @summary Get thermo data for optimization
 */
export const useGetThermoDataOptimizationOptIdThermoDataGet = <TError = Promise<HTTPValidationError>>(
  optId: number,
    params?: GetThermoDataOptimizationOptIdThermoDataGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getThermoDataOptimizationOptIdThermoDataGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(optId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetThermoDataOptimizationOptIdThermoDataGetKey(optId,params) : null);
  const swrFn = () => getThermoDataOptimizationOptIdThermoDataGet(optId,params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Update thermo data
 */
export type updateThermoDataOptimizationOptIdThermoDataPatchResponse200 = {
  data: ThermoData
  status: 200
}

export type updateThermoDataOptimizationOptIdThermoDataPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type updateThermoDataOptimizationOptIdThermoDataPatchResponseSuccess = (updateThermoDataOptimizationOptIdThermoDataPatchResponse200) & {
  headers: Headers;
};
export type updateThermoDataOptimizationOptIdThermoDataPatchResponseError = (updateThermoDataOptimizationOptIdThermoDataPatchResponse422) & {
  headers: Headers;
};

export type updateThermoDataOptimizationOptIdThermoDataPatchResponse = (updateThermoDataOptimizationOptIdThermoDataPatchResponseSuccess | updateThermoDataOptimizationOptIdThermoDataPatchResponseError)

export const getUpdateThermoDataOptimizationOptIdThermoDataPatchUrl = (optId: number,) => {


  

  return `/optimization/${optId}/thermo_data`
}

export const updateThermoDataOptimizationOptIdThermoDataPatch = async (optId: number,
    updateThermoDataOptimizationOptIdThermoDataPatchBody: UpdateThermoDataOptimizationOptIdThermoDataPatchBody, options?: RequestInit): Promise<updateThermoDataOptimizationOptIdThermoDataPatchResponse> => {
  
  const res = await fetch(getUpdateThermoDataOptimizationOptIdThermoDataPatchUrl(optId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateThermoDataOptimizationOptIdThermoDataPatchBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateThermoDataOptimizationOptIdThermoDataPatchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateThermoDataOptimizationOptIdThermoDataPatchResponse
}




export const getUpdateThermoDataOptimizationOptIdThermoDataPatchMutationFetcher = (optId: number, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: UpdateThermoDataOptimizationOptIdThermoDataPatchBody }) => {
    return updateThermoDataOptimizationOptIdThermoDataPatch(optId, arg, options);
  }
}
export const getUpdateThermoDataOptimizationOptIdThermoDataPatchMutationKey = (optId: number,) => [`/optimization/${optId}/thermo_data`] as const;

export type UpdateThermoDataOptimizationOptIdThermoDataPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateThermoDataOptimizationOptIdThermoDataPatch>>>
export type UpdateThermoDataOptimizationOptIdThermoDataPatchMutationError = Promise<HTTPValidationError>

/**
 * @summary Update thermo data
 */
export const useUpdateThermoDataOptimizationOptIdThermoDataPatch = <TError = Promise<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateThermoDataOptimizationOptIdThermoDataPatch>>, TError, Key, UpdateThermoDataOptimizationOptIdThermoDataPatchBody, Awaited<ReturnType<typeof updateThermoDataOptimizationOptIdThermoDataPatch>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateThermoDataOptimizationOptIdThermoDataPatchMutationKey(optId);
  const swrFn = getUpdateThermoDataOptimizationOptIdThermoDataPatchMutationFetcher(optId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
