/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  GetThermoDataOptimizationOptIdThermoDataGetParams,
  HTTPValidationError,
  ThermoData,
  UpdateThermoDataOptimizationOptIdThermoDataPatchBody
} from '.././model';



  
  
  
/**
 * @summary Get thermo data for optimization
 */
export const getThermoDataOptimizationOptIdThermoDataGet = (
    optId: number,
    params?: GetThermoDataOptimizationOptIdThermoDataGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ThermoData>> => {
    return axios.get(
      `/optimization/${optId}/thermo_data`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getGetThermoDataOptimizationOptIdThermoDataGetKey = (optId: number,
    params?: GetThermoDataOptimizationOptIdThermoDataGetParams,) => [`/optimization/${optId}/thermo_data`, ...(params ? [params]: [])] as const;

export type GetThermoDataOptimizationOptIdThermoDataGetQueryResult = NonNullable<Awaited<ReturnType<typeof getThermoDataOptimizationOptIdThermoDataGet>>>
export type GetThermoDataOptimizationOptIdThermoDataGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get thermo data for optimization
 */
export const useGetThermoDataOptimizationOptIdThermoDataGet = <TError = AxiosError<HTTPValidationError>>(
  optId: number,
    params?: GetThermoDataOptimizationOptIdThermoDataGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getThermoDataOptimizationOptIdThermoDataGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(optId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetThermoDataOptimizationOptIdThermoDataGetKey(optId,params) : null);
  const swrFn = () => getThermoDataOptimizationOptIdThermoDataGet(optId,params, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Update thermo data
 */
export const updateThermoDataOptimizationOptIdThermoDataPatch = (
    optId: number,
    updateThermoDataOptimizationOptIdThermoDataPatchBody: UpdateThermoDataOptimizationOptIdThermoDataPatchBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ThermoData>> => {
    return axios.patch(
      `/optimization/${optId}/thermo_data`,
      updateThermoDataOptimizationOptIdThermoDataPatchBody,options
    );
  }



export const getUpdateThermoDataOptimizationOptIdThermoDataPatchMutationFetcher = (optId: number, options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: UpdateThermoDataOptimizationOptIdThermoDataPatchBody }) => {
    return updateThermoDataOptimizationOptIdThermoDataPatch(optId, arg, options);
  }
}
export const getUpdateThermoDataOptimizationOptIdThermoDataPatchMutationKey = (optId: number,) => [`/optimization/${optId}/thermo_data`] as const;

export type UpdateThermoDataOptimizationOptIdThermoDataPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateThermoDataOptimizationOptIdThermoDataPatch>>>
export type UpdateThermoDataOptimizationOptIdThermoDataPatchMutationError = AxiosError<HTTPValidationError>

/**
 * @summary Update thermo data
 */
export const useUpdateThermoDataOptimizationOptIdThermoDataPatch = <TError = AxiosError<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateThermoDataOptimizationOptIdThermoDataPatch>>, TError, Key, UpdateThermoDataOptimizationOptIdThermoDataPatchBody, Awaited<ReturnType<typeof updateThermoDataOptimizationOptIdThermoDataPatch>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateThermoDataOptimizationOptIdThermoDataPatchMutationKey(optId);
  const swrFn = getUpdateThermoDataOptimizationOptIdThermoDataPatchMutationFetcher(optId, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
