/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  ThermoData
} from '.././model';


export const getGetThermoDataOptimizationOptIdThermoDataGetResponseMock = (overrideResponse: Partial< ThermoData > = {}): ThermoData => ({thermal_transmittance_external_walls: faker.number.float({min: 0, max: 10, fractionDigits: 2}), thermal_transmittance_doors: faker.number.float({min: 0, max: 10, fractionDigits: 2}), thermal_transmittance_windows: faker.number.float({min: 0, max: 10, fractionDigits: 2}), thermal_transmittance_roof_windows: faker.number.float({min: 0, max: 10, fractionDigits: 2}), thermal_transmittance_foundation: faker.number.float({min: 0, max: 10, fractionDigits: 2}), thermal_transmittance_roof: faker.number.float({min: 0, max: 10, fractionDigits: 2}), ventilation_heat_recovery_efficiency: faker.number.float({min: 0, max: 1, fractionDigits: 2}), ...overrideResponse})

export const getUpdateThermoDataOptimizationOptIdThermoDataPatchResponseMock = (overrideResponse: Partial< ThermoData > = {}): ThermoData => ({thermal_transmittance_external_walls: faker.number.float({min: 0, max: 10, fractionDigits: 2}), thermal_transmittance_doors: faker.number.float({min: 0, max: 10, fractionDigits: 2}), thermal_transmittance_windows: faker.number.float({min: 0, max: 10, fractionDigits: 2}), thermal_transmittance_roof_windows: faker.number.float({min: 0, max: 10, fractionDigits: 2}), thermal_transmittance_foundation: faker.number.float({min: 0, max: 10, fractionDigits: 2}), thermal_transmittance_roof: faker.number.float({min: 0, max: 10, fractionDigits: 2}), ventilation_heat_recovery_efficiency: faker.number.float({min: 0, max: 1, fractionDigits: 2}), ...overrideResponse})


export const getGetThermoDataOptimizationOptIdThermoDataGetMockHandler = (overrideResponse?: ThermoData | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ThermoData> | ThermoData), options?: RequestHandlerOptions) => {
  return http.get('*/optimization/:optId/thermo_data', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetThermoDataOptimizationOptIdThermoDataGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateThermoDataOptimizationOptIdThermoDataPatchMockHandler = (overrideResponse?: ThermoData | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<ThermoData> | ThermoData), options?: RequestHandlerOptions) => {
  return http.patch('*/optimization/:optId/thermo_data', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateThermoDataOptimizationOptIdThermoDataPatchResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getOptimizationThermoDataMock = () => [
  getGetThermoDataOptimizationOptIdThermoDataGetMockHandler(),
  getUpdateThermoDataOptimizationOptIdThermoDataPatchMockHandler()
]
