/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  BodyUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch,
  GetBuildingDataOptimizationOptIdBuildingDataGetParams,
  HTTPValidationError,
  ObjectData,
  StateResponse,
  UpdateBuildingDataOptimizationOptIdBuildingDataPatchBody
} from '.././model';



  
  
  
/**
 * @summary Update address point id
 */
export type updateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchResponse200 = {
  data: StateResponse
  status: 200
}

export type updateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type updateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchResponseSuccess = (updateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchResponse200) & {
  headers: Headers;
};
export type updateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchResponseError = (updateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchResponse422) & {
  headers: Headers;
};

export type updateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchResponse = (updateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchResponseSuccess | updateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchResponseError)

export const getUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchUrl = (optId: number,) => {


  

  return `/optimization/${optId}/building_data/address_id`
}

export const updateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch = async (optId: number,
    bodyUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch: BodyUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch, options?: RequestInit): Promise<updateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchResponse> => {
  
  const res = await fetch(getUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchUrl(optId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bodyUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchResponse
}




export const getUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchMutationFetcher = (optId: number, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: BodyUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch }) => {
    return updateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch(optId, arg, options);
  }
}
export const getUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchMutationKey = (optId: number,) => [`/optimization/${optId}/building_data/address_id`] as const;

export type UpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch>>>
export type UpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchMutationError = Promise<HTTPValidationError>

/**
 * @summary Update address point id
 */
export const useUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch = <TError = Promise<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch>>, TError, Key, BodyUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch, Awaited<ReturnType<typeof updateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchMutationKey(optId);
  const swrFn = getUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchMutationFetcher(optId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get building data by address
 */
export type getBuildingDataOptimizationOptIdBuildingDataGetResponse200 = {
  data: ObjectData
  status: 200
}

export type getBuildingDataOptimizationOptIdBuildingDataGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getBuildingDataOptimizationOptIdBuildingDataGetResponseSuccess = (getBuildingDataOptimizationOptIdBuildingDataGetResponse200) & {
  headers: Headers;
};
export type getBuildingDataOptimizationOptIdBuildingDataGetResponseError = (getBuildingDataOptimizationOptIdBuildingDataGetResponse422) & {
  headers: Headers;
};

export type getBuildingDataOptimizationOptIdBuildingDataGetResponse = (getBuildingDataOptimizationOptIdBuildingDataGetResponseSuccess | getBuildingDataOptimizationOptIdBuildingDataGetResponseError)

export const getGetBuildingDataOptimizationOptIdBuildingDataGetUrl = (optId: number,
    params?: GetBuildingDataOptimizationOptIdBuildingDataGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/optimization/${optId}/building_data?${stringifiedParams}` : `/optimization/${optId}/building_data`
}

export const getBuildingDataOptimizationOptIdBuildingDataGet = async (optId: number,
    params?: GetBuildingDataOptimizationOptIdBuildingDataGetParams, options?: RequestInit): Promise<getBuildingDataOptimizationOptIdBuildingDataGetResponse> => {
  
  const res = await fetch(getGetBuildingDataOptimizationOptIdBuildingDataGetUrl(optId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getBuildingDataOptimizationOptIdBuildingDataGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getBuildingDataOptimizationOptIdBuildingDataGetResponse
}




export const getGetBuildingDataOptimizationOptIdBuildingDataGetKey = (optId: number,
    params?: GetBuildingDataOptimizationOptIdBuildingDataGetParams,) => [`/optimization/${optId}/building_data`, ...(params ? [params]: [])] as const;

export type GetBuildingDataOptimizationOptIdBuildingDataGetQueryResult = NonNullable<Awaited<ReturnType<typeof getBuildingDataOptimizationOptIdBuildingDataGet>>>
export type GetBuildingDataOptimizationOptIdBuildingDataGetQueryError = Promise<HTTPValidationError>

/**
 * @summary Get building data by address
 */
export const useGetBuildingDataOptimizationOptIdBuildingDataGet = <TError = Promise<HTTPValidationError>>(
  optId: number,
    params?: GetBuildingDataOptimizationOptIdBuildingDataGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getBuildingDataOptimizationOptIdBuildingDataGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(optId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetBuildingDataOptimizationOptIdBuildingDataGetKey(optId,params) : null);
  const swrFn = () => getBuildingDataOptimizationOptIdBuildingDataGet(optId,params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Update building data
 */
export type updateBuildingDataOptimizationOptIdBuildingDataPatchResponse200 = {
  data: ObjectData
  status: 200
}

export type updateBuildingDataOptimizationOptIdBuildingDataPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type updateBuildingDataOptimizationOptIdBuildingDataPatchResponseSuccess = (updateBuildingDataOptimizationOptIdBuildingDataPatchResponse200) & {
  headers: Headers;
};
export type updateBuildingDataOptimizationOptIdBuildingDataPatchResponseError = (updateBuildingDataOptimizationOptIdBuildingDataPatchResponse422) & {
  headers: Headers;
};

export type updateBuildingDataOptimizationOptIdBuildingDataPatchResponse = (updateBuildingDataOptimizationOptIdBuildingDataPatchResponseSuccess | updateBuildingDataOptimizationOptIdBuildingDataPatchResponseError)

export const getUpdateBuildingDataOptimizationOptIdBuildingDataPatchUrl = (optId: number,) => {


  

  return `/optimization/${optId}/building_data`
}

export const updateBuildingDataOptimizationOptIdBuildingDataPatch = async (optId: number,
    updateBuildingDataOptimizationOptIdBuildingDataPatchBody: UpdateBuildingDataOptimizationOptIdBuildingDataPatchBody, options?: RequestInit): Promise<updateBuildingDataOptimizationOptIdBuildingDataPatchResponse> => {
  
  const res = await fetch(getUpdateBuildingDataOptimizationOptIdBuildingDataPatchUrl(optId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateBuildingDataOptimizationOptIdBuildingDataPatchBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateBuildingDataOptimizationOptIdBuildingDataPatchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateBuildingDataOptimizationOptIdBuildingDataPatchResponse
}




export const getUpdateBuildingDataOptimizationOptIdBuildingDataPatchMutationFetcher = (optId: number, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: UpdateBuildingDataOptimizationOptIdBuildingDataPatchBody }) => {
    return updateBuildingDataOptimizationOptIdBuildingDataPatch(optId, arg, options);
  }
}
export const getUpdateBuildingDataOptimizationOptIdBuildingDataPatchMutationKey = (optId: number,) => [`/optimization/${optId}/building_data`] as const;

export type UpdateBuildingDataOptimizationOptIdBuildingDataPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateBuildingDataOptimizationOptIdBuildingDataPatch>>>
export type UpdateBuildingDataOptimizationOptIdBuildingDataPatchMutationError = Promise<HTTPValidationError>

/**
 * @summary Update building data
 */
export const useUpdateBuildingDataOptimizationOptIdBuildingDataPatch = <TError = Promise<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateBuildingDataOptimizationOptIdBuildingDataPatch>>, TError, Key, UpdateBuildingDataOptimizationOptIdBuildingDataPatchBody, Awaited<ReturnType<typeof updateBuildingDataOptimizationOptIdBuildingDataPatch>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateBuildingDataOptimizationOptIdBuildingDataPatchMutationKey(optId);
  const swrFn = getUpdateBuildingDataOptimizationOptIdBuildingDataPatchMutationFetcher(optId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
