/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import {
  BuildingType,
  Operator,
  Tariff
} from '.././model';
import type {
  ObjectData,
  StateResponse
} from '.././model';


export const getUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchResponseMock = (): StateResponse => (faker.helpers.arrayElement(['SUCCESS','ERROR'] as const))

export const getGetBuildingDataOptimizationOptIdBuildingDataGetResponseMock = (overrideResponse: Partial< ObjectData > = {}): ObjectData => ({building_type: faker.helpers.arrayElement(Object.values(BuildingType)), build_year: faker.number.int({min: undefined, max: undefined}), usable_area: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), number_of_floors: faker.number.int({min: undefined, max: undefined}), number_of_residents: faker.number.int({min: undefined, max: undefined}), total_external_wall_area: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), total_window_area: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), total_roof_window_area: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), total_external_door_area: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), total_roof_area: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), foundation_area: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), volume: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), air_exchange_rate: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), roof_angle: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), operator: faker.helpers.arrayElement(Object.values(Operator)), tariff: faker.helpers.arrayElement(Object.values(Tariff)), ...overrideResponse})

export const getUpdateBuildingDataOptimizationOptIdBuildingDataPatchResponseMock = (overrideResponse: Partial< ObjectData > = {}): ObjectData => ({building_type: faker.helpers.arrayElement(Object.values(BuildingType)), build_year: faker.number.int({min: undefined, max: undefined}), usable_area: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), number_of_floors: faker.number.int({min: undefined, max: undefined}), number_of_residents: faker.number.int({min: undefined, max: undefined}), total_external_wall_area: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), total_window_area: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), total_roof_window_area: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), total_external_door_area: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), total_roof_area: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), foundation_area: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), volume: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), air_exchange_rate: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), roof_angle: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), operator: faker.helpers.arrayElement(Object.values(Operator)), tariff: faker.helpers.arrayElement(Object.values(Tariff)), ...overrideResponse})


export const getUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchMockHandler = (overrideResponse?: StateResponse | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<StateResponse> | StateResponse), options?: RequestHandlerOptions) => {
  return http.patch('*/optimization/:optId/building_data/address_id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetBuildingDataOptimizationOptIdBuildingDataGetMockHandler = (overrideResponse?: ObjectData | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ObjectData> | ObjectData), options?: RequestHandlerOptions) => {
  return http.get('*/optimization/:optId/building_data', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetBuildingDataOptimizationOptIdBuildingDataGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateBuildingDataOptimizationOptIdBuildingDataPatchMockHandler = (overrideResponse?: ObjectData | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<ObjectData> | ObjectData), options?: RequestHandlerOptions) => {
  return http.patch('*/optimization/:optId/building_data', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateBuildingDataOptimizationOptIdBuildingDataPatchResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getOptimizationBuildingDataMock = () => [
  getUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchMockHandler(),
  getGetBuildingDataOptimizationOptIdBuildingDataGetMockHandler(),
  getUpdateBuildingDataOptimizationOptIdBuildingDataPatchMockHandler()
]
