/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  BodyUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch,
  GetBuildingDataOptimizationOptIdBuildingDataGetParams,
  HTTPValidationError,
  ObjectData,
  StateResponse,
  UpdateBuildingDataOptimizationOptIdBuildingDataPatchBody
} from '.././model';



  
  
  
/**
 * @summary Update address point id
 */
export const updateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch = (
    optId: number,
    bodyUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch: BodyUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StateResponse>> => {
    return axios.patch(
      `/optimization/${optId}/building_data/address_id`,
      bodyUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch,options
    );
  }



export const getUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchMutationFetcher = (optId: number, options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: BodyUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch }) => {
    return updateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch(optId, arg, options);
  }
}
export const getUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchMutationKey = (optId: number,) => [`/optimization/${optId}/building_data/address_id`] as const;

export type UpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch>>>
export type UpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchMutationError = AxiosError<HTTPValidationError>

/**
 * @summary Update address point id
 */
export const useUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch = <TError = AxiosError<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch>>, TError, Key, BodyUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch, Awaited<ReturnType<typeof updateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatch>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchMutationKey(optId);
  const swrFn = getUpdateAddressPointIdOptimizationOptIdBuildingDataAddressIdPatchMutationFetcher(optId, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Get building data by address
 */
export const getBuildingDataOptimizationOptIdBuildingDataGet = (
    optId: number,
    params?: GetBuildingDataOptimizationOptIdBuildingDataGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ObjectData>> => {
    return axios.get(
      `/optimization/${optId}/building_data`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getGetBuildingDataOptimizationOptIdBuildingDataGetKey = (optId: number,
    params?: GetBuildingDataOptimizationOptIdBuildingDataGetParams,) => [`/optimization/${optId}/building_data`, ...(params ? [params]: [])] as const;

export type GetBuildingDataOptimizationOptIdBuildingDataGetQueryResult = NonNullable<Awaited<ReturnType<typeof getBuildingDataOptimizationOptIdBuildingDataGet>>>
export type GetBuildingDataOptimizationOptIdBuildingDataGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get building data by address
 */
export const useGetBuildingDataOptimizationOptIdBuildingDataGet = <TError = AxiosError<HTTPValidationError>>(
  optId: number,
    params?: GetBuildingDataOptimizationOptIdBuildingDataGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getBuildingDataOptimizationOptIdBuildingDataGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(optId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetBuildingDataOptimizationOptIdBuildingDataGetKey(optId,params) : null);
  const swrFn = () => getBuildingDataOptimizationOptIdBuildingDataGet(optId,params, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Update building data
 */
export const updateBuildingDataOptimizationOptIdBuildingDataPatch = (
    optId: number,
    updateBuildingDataOptimizationOptIdBuildingDataPatchBody: UpdateBuildingDataOptimizationOptIdBuildingDataPatchBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ObjectData>> => {
    return axios.patch(
      `/optimization/${optId}/building_data`,
      updateBuildingDataOptimizationOptIdBuildingDataPatchBody,options
    );
  }



export const getUpdateBuildingDataOptimizationOptIdBuildingDataPatchMutationFetcher = (optId: number, options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: UpdateBuildingDataOptimizationOptIdBuildingDataPatchBody }) => {
    return updateBuildingDataOptimizationOptIdBuildingDataPatch(optId, arg, options);
  }
}
export const getUpdateBuildingDataOptimizationOptIdBuildingDataPatchMutationKey = (optId: number,) => [`/optimization/${optId}/building_data`] as const;

export type UpdateBuildingDataOptimizationOptIdBuildingDataPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateBuildingDataOptimizationOptIdBuildingDataPatch>>>
export type UpdateBuildingDataOptimizationOptIdBuildingDataPatchMutationError = AxiosError<HTTPValidationError>

/**
 * @summary Update building data
 */
export const useUpdateBuildingDataOptimizationOptIdBuildingDataPatch = <TError = AxiosError<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateBuildingDataOptimizationOptIdBuildingDataPatch>>, TError, Key, UpdateBuildingDataOptimizationOptIdBuildingDataPatchBody, Awaited<ReturnType<typeof updateBuildingDataOptimizationOptIdBuildingDataPatch>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateBuildingDataOptimizationOptIdBuildingDataPatchMutationKey(optId);
  const swrFn = getUpdateBuildingDataOptimizationOptIdBuildingDataPatchMutationFetcher(optId, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
