/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  AuthenticateUserUsersAuthenticateGetParams,
  HTTPValidationError,
  StateResponse,
  UserModel
} from '.././model';



  
  
  
/**
 * Returns user data
 * @summary Get User
 */
export const getUserUsersMeGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserModel>> => {
    return axios.get(
      `/users/me`,options
    );
  }



export const getGetUserUsersMeGetKey = () => [`/users/me`] as const;

export type GetUserUsersMeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getUserUsersMeGet>>>
export type GetUserUsersMeGetQueryError = AxiosError<unknown>

/**
 * @summary Get User
 */
export const useGetUserUsersMeGet = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getUserUsersMeGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetUserUsersMeGetKey() : null);
  const swrFn = () => getUserUsersMeGet(axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Creates new user
 * @summary Clear User
 */
export const clearUserUsersClearGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StateResponse>> => {
    return axios.get(
      `/users/clear`,options
    );
  }



export const getClearUserUsersClearGetKey = () => [`/users/clear`] as const;

export type ClearUserUsersClearGetQueryResult = NonNullable<Awaited<ReturnType<typeof clearUserUsersClearGet>>>
export type ClearUserUsersClearGetQueryError = AxiosError<unknown>

/**
 * @summary Clear User
 */
export const useClearUserUsersClearGet = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof clearUserUsersClearGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getClearUserUsersClearGetKey() : null);
  const swrFn = () => clearUserUsersClearGet(axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Authenticates user with auth token
 * @summary Authenticate User
 */
export const authenticateUserUsersAuthenticateGet = (
    params: AuthenticateUserUsersAuthenticateGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StateResponse>> => {
    return axios.get(
      `/users/authenticate`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getAuthenticateUserUsersAuthenticateGetKey = (params: AuthenticateUserUsersAuthenticateGetParams,) => [`/users/authenticate`, ...(params ? [params]: [])] as const;

export type AuthenticateUserUsersAuthenticateGetQueryResult = NonNullable<Awaited<ReturnType<typeof authenticateUserUsersAuthenticateGet>>>
export type AuthenticateUserUsersAuthenticateGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Authenticate User
 */
export const useAuthenticateUserUsersAuthenticateGet = <TError = AxiosError<HTTPValidationError>>(
  params: AuthenticateUserUsersAuthenticateGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof authenticateUserUsersAuthenticateGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getAuthenticateUserUsersAuthenticateGetKey(params) : null);
  const swrFn = () => authenticateUserUsersAuthenticateGet(params, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Returns auth token
 * @summary Get Auth Token
 */
export const getAuthTokenUsersGetAuthTokenGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    return axios.get(
      `/users/get_auth_token`,{
        responseType: 'text',
    ...options,}
    );
  }



export const getGetAuthTokenUsersGetAuthTokenGetKey = () => [`/users/get_auth_token`] as const;

export type GetAuthTokenUsersGetAuthTokenGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthTokenUsersGetAuthTokenGet>>>
export type GetAuthTokenUsersGetAuthTokenGetQueryError = AxiosError<unknown>

/**
 * @summary Get Auth Token
 */
export const useGetAuthTokenUsersGetAuthTokenGet = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAuthTokenUsersGetAuthTokenGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAuthTokenUsersGetAuthTokenGetKey() : null);
  const swrFn = () => getAuthTokenUsersGetAuthTokenGet(axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
