/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  AuthenticateUserUsersAuthenticateGetParams,
  HTTPValidationError,
  StateResponse,
  UserModel
} from '.././model';



  
  
  
/**
 * Returns user data
 * @summary Get User
 */
export type getUserUsersMeGetResponse200 = {
  data: UserModel
  status: 200
}
    
export type getUserUsersMeGetResponseSuccess = (getUserUsersMeGetResponse200) & {
  headers: Headers;
};
;

export type getUserUsersMeGetResponse = (getUserUsersMeGetResponseSuccess)

export const getGetUserUsersMeGetUrl = () => {


  

  return `/users/me`
}

export const getUserUsersMeGet = async ( options?: RequestInit): Promise<getUserUsersMeGetResponse> => {
  
  const res = await fetch(getGetUserUsersMeGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getUserUsersMeGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUserUsersMeGetResponse
}




export const getGetUserUsersMeGetKey = () => [`/users/me`] as const;

export type GetUserUsersMeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getUserUsersMeGet>>>
export type GetUserUsersMeGetQueryError = Promise<unknown>

/**
 * @summary Get User
 */
export const useGetUserUsersMeGet = <TError = Promise<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getUserUsersMeGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetUserUsersMeGetKey() : null);
  const swrFn = () => getUserUsersMeGet(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Creates new user
 * @summary Clear User
 */
export type clearUserUsersClearGetResponse200 = {
  data: StateResponse
  status: 200
}
    
export type clearUserUsersClearGetResponseSuccess = (clearUserUsersClearGetResponse200) & {
  headers: Headers;
};
;

export type clearUserUsersClearGetResponse = (clearUserUsersClearGetResponseSuccess)

export const getClearUserUsersClearGetUrl = () => {


  

  return `/users/clear`
}

export const clearUserUsersClearGet = async ( options?: RequestInit): Promise<clearUserUsersClearGetResponse> => {
  
  const res = await fetch(getClearUserUsersClearGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: clearUserUsersClearGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as clearUserUsersClearGetResponse
}




export const getClearUserUsersClearGetKey = () => [`/users/clear`] as const;

export type ClearUserUsersClearGetQueryResult = NonNullable<Awaited<ReturnType<typeof clearUserUsersClearGet>>>
export type ClearUserUsersClearGetQueryError = Promise<unknown>

/**
 * @summary Clear User
 */
export const useClearUserUsersClearGet = <TError = Promise<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof clearUserUsersClearGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getClearUserUsersClearGetKey() : null);
  const swrFn = () => clearUserUsersClearGet(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Authenticates user with auth token
 * @summary Authenticate User
 */
export type authenticateUserUsersAuthenticateGetResponse200 = {
  data: StateResponse
  status: 200
}

export type authenticateUserUsersAuthenticateGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type authenticateUserUsersAuthenticateGetResponseSuccess = (authenticateUserUsersAuthenticateGetResponse200) & {
  headers: Headers;
};
export type authenticateUserUsersAuthenticateGetResponseError = (authenticateUserUsersAuthenticateGetResponse422) & {
  headers: Headers;
};

export type authenticateUserUsersAuthenticateGetResponse = (authenticateUserUsersAuthenticateGetResponseSuccess | authenticateUserUsersAuthenticateGetResponseError)

export const getAuthenticateUserUsersAuthenticateGetUrl = (params: AuthenticateUserUsersAuthenticateGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/users/authenticate?${stringifiedParams}` : `/users/authenticate`
}

export const authenticateUserUsersAuthenticateGet = async (params: AuthenticateUserUsersAuthenticateGetParams, options?: RequestInit): Promise<authenticateUserUsersAuthenticateGetResponse> => {
  
  const res = await fetch(getAuthenticateUserUsersAuthenticateGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authenticateUserUsersAuthenticateGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authenticateUserUsersAuthenticateGetResponse
}




export const getAuthenticateUserUsersAuthenticateGetKey = (params: AuthenticateUserUsersAuthenticateGetParams,) => [`/users/authenticate`, ...(params ? [params]: [])] as const;

export type AuthenticateUserUsersAuthenticateGetQueryResult = NonNullable<Awaited<ReturnType<typeof authenticateUserUsersAuthenticateGet>>>
export type AuthenticateUserUsersAuthenticateGetQueryError = Promise<HTTPValidationError>

/**
 * @summary Authenticate User
 */
export const useAuthenticateUserUsersAuthenticateGet = <TError = Promise<HTTPValidationError>>(
  params: AuthenticateUserUsersAuthenticateGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof authenticateUserUsersAuthenticateGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getAuthenticateUserUsersAuthenticateGetKey(params) : null);
  const swrFn = () => authenticateUserUsersAuthenticateGet(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Returns auth token
 * @summary Get Auth Token
 */
export type getAuthTokenUsersGetAuthTokenGetResponse200 = {
  data: string
  status: 200
}
    
export type getAuthTokenUsersGetAuthTokenGetResponseSuccess = (getAuthTokenUsersGetAuthTokenGetResponse200) & {
  headers: Headers;
};
;

export type getAuthTokenUsersGetAuthTokenGetResponse = (getAuthTokenUsersGetAuthTokenGetResponseSuccess)

export const getGetAuthTokenUsersGetAuthTokenGetUrl = () => {


  

  return `/users/get_auth_token`
}

export const getAuthTokenUsersGetAuthTokenGet = async ( options?: RequestInit): Promise<getAuthTokenUsersGetAuthTokenGetResponse> => {
  
  const res = await fetch(getGetAuthTokenUsersGetAuthTokenGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAuthTokenUsersGetAuthTokenGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAuthTokenUsersGetAuthTokenGetResponse
}




export const getGetAuthTokenUsersGetAuthTokenGetKey = () => [`/users/get_auth_token`] as const;

export type GetAuthTokenUsersGetAuthTokenGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthTokenUsersGetAuthTokenGet>>>
export type GetAuthTokenUsersGetAuthTokenGetQueryError = Promise<unknown>

/**
 * @summary Get Auth Token
 */
export const useGetAuthTokenUsersGetAuthTokenGet = <TError = Promise<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAuthTokenUsersGetAuthTokenGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAuthTokenUsersGetAuthTokenGetKey() : null);
  const swrFn = () => getAuthTokenUsersGetAuthTokenGet(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
