/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  StateResponse,
  UserModel
} from '.././model';


export const getGetUserUsersMeGetResponseMock = (overrideResponse: Partial< UserModel > = {}): UserModel => ({uid: faker.string.uuid(), sync_params: {timestamp: `${faker.date.past().toISOString().split('.')[0]}Z`, request_count: faker.number.int({min: undefined, max: undefined})}, ip_address: faker.string.alpha({length: {min: 10, max: 20}}), last_active: `${faker.date.past().toISOString().split('.')[0]}Z`, request_count: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getClearUserUsersClearGetResponseMock = (): StateResponse => (faker.helpers.arrayElement(['SUCCESS','ERROR'] as const))

export const getAuthenticateUserUsersAuthenticateGetResponseMock = (): StateResponse => (faker.helpers.arrayElement(['SUCCESS','ERROR'] as const))

export const getGetAuthTokenUsersGetAuthTokenGetResponseMock = (): string => (faker.word.sample())


export const getGetUserUsersMeGetMockHandler = (overrideResponse?: UserModel | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<UserModel> | UserModel), options?: RequestHandlerOptions) => {
  return http.get('*/users/me', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetUserUsersMeGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getClearUserUsersClearGetMockHandler = (overrideResponse?: StateResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<StateResponse> | StateResponse), options?: RequestHandlerOptions) => {
  return http.get('*/users/clear', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getClearUserUsersClearGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getAuthenticateUserUsersAuthenticateGetMockHandler = (overrideResponse?: StateResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<StateResponse> | StateResponse), options?: RequestHandlerOptions) => {
  return http.get('*/users/authenticate', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAuthenticateUserUsersAuthenticateGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetAuthTokenUsersGetAuthTokenGetMockHandler = (overrideResponse?: string | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<string> | string), options?: RequestHandlerOptions) => {
  return http.get('*/users/get_auth_token', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetAuthTokenUsersGetAuthTokenGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getUsersMock = () => [
  getGetUserUsersMeGetMockHandler(),
  getClearUserUsersClearGetMockHandler(),
  getAuthenticateUserUsersAuthenticateGetMockHandler(),
  getGetAuthTokenUsersGetAuthTokenGetMockHandler()
]
