/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  AppInfoModel,
  GetFuelsInfoFuelsGet200,
  GetTechnologiesInfoTechnologiesGet200,
  GetThermoLevelsInfoThermoLevelsGet200,
  Operator,
  Tariff
} from '.././model';



  
  
  
/**
 * @summary Returns info about app
 */
export const getAppInfoInfoGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AppInfoModel>> => {
    return axios.get(
      `/info`,options
    );
  }



export const getGetAppInfoInfoGetKey = () => [`/info`] as const;

export type GetAppInfoInfoGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAppInfoInfoGet>>>
export type GetAppInfoInfoGetQueryError = AxiosError<unknown>

/**
 * @summary Returns info about app
 */
export const useGetAppInfoInfoGet = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAppInfoInfoGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAppInfoInfoGetKey() : null);
  const swrFn = () => getAppInfoInfoGet(axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Returns list of operators
 */
export const getOperatorsInfoOperatorsGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Operator[]>> => {
    return axios.get(
      `/info/operators`,options
    );
  }



export const getGetOperatorsInfoOperatorsGetKey = () => [`/info/operators`] as const;

export type GetOperatorsInfoOperatorsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getOperatorsInfoOperatorsGet>>>
export type GetOperatorsInfoOperatorsGetQueryError = AxiosError<unknown>

/**
 * @summary Returns list of operators
 */
export const useGetOperatorsInfoOperatorsGet = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getOperatorsInfoOperatorsGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetOperatorsInfoOperatorsGetKey() : null);
  const swrFn = () => getOperatorsInfoOperatorsGet(axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Returns list of tariffs
 */
export const getTariffsInfoTariffsGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Tariff[]>> => {
    return axios.get(
      `/info/tariffs`,options
    );
  }



export const getGetTariffsInfoTariffsGetKey = () => [`/info/tariffs`] as const;

export type GetTariffsInfoTariffsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTariffsInfoTariffsGet>>>
export type GetTariffsInfoTariffsGetQueryError = AxiosError<unknown>

/**
 * @summary Returns list of tariffs
 */
export const useGetTariffsInfoTariffsGet = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getTariffsInfoTariffsGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetTariffsInfoTariffsGetKey() : null);
  const swrFn = () => getTariffsInfoTariffsGet(axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Returns list of technologies
 */
export const getTechnologiesInfoTechnologiesGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetTechnologiesInfoTechnologiesGet200>> => {
    return axios.get(
      `/info/technologies`,options
    );
  }



export const getGetTechnologiesInfoTechnologiesGetKey = () => [`/info/technologies`] as const;

export type GetTechnologiesInfoTechnologiesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTechnologiesInfoTechnologiesGet>>>
export type GetTechnologiesInfoTechnologiesGetQueryError = AxiosError<unknown>

/**
 * @summary Returns list of technologies
 */
export const useGetTechnologiesInfoTechnologiesGet = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getTechnologiesInfoTechnologiesGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetTechnologiesInfoTechnologiesGetKey() : null);
  const swrFn = () => getTechnologiesInfoTechnologiesGet(axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Returns list of fuels
 */
export const getFuelsInfoFuelsGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetFuelsInfoFuelsGet200>> => {
    return axios.get(
      `/info/fuels`,options
    );
  }



export const getGetFuelsInfoFuelsGetKey = () => [`/info/fuels`] as const;

export type GetFuelsInfoFuelsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getFuelsInfoFuelsGet>>>
export type GetFuelsInfoFuelsGetQueryError = AxiosError<unknown>

/**
 * @summary Returns list of fuels
 */
export const useGetFuelsInfoFuelsGet = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getFuelsInfoFuelsGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetFuelsInfoFuelsGetKey() : null);
  const swrFn = () => getFuelsInfoFuelsGet(axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Returns list of thermo levels for each building partition
 */
export const getThermoLevelsInfoThermoLevelsGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetThermoLevelsInfoThermoLevelsGet200>> => {
    return axios.get(
      `/info/thermo_levels`,options
    );
  }



export const getGetThermoLevelsInfoThermoLevelsGetKey = () => [`/info/thermo_levels`] as const;

export type GetThermoLevelsInfoThermoLevelsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getThermoLevelsInfoThermoLevelsGet>>>
export type GetThermoLevelsInfoThermoLevelsGetQueryError = AxiosError<unknown>

/**
 * @summary Returns list of thermo levels for each building partition
 */
export const useGetThermoLevelsInfoThermoLevelsGet = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getThermoLevelsInfoThermoLevelsGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetThermoLevelsInfoThermoLevelsGetKey() : null);
  const swrFn = () => getThermoLevelsInfoThermoLevelsGet(axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
