/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import {
  Operator,
  Tariff
} from '.././model';
import type {
  AppInfoModel,
  GetFuelsInfoFuelsGet200,
  GetTechnologiesInfoTechnologiesGet200,
  GetThermoLevelsInfoThermoLevelsGet200
} from '.././model';


export const getGetAppInfoInfoGetResponseMock = (overrideResponse: Partial< AppInfoModel > = {}): AppInfoModel => ({name: faker.string.alpha({length: {min: 10, max: 20}}), version: faker.string.alpha({length: {min: 10, max: 20}}), users_today: faker.number.int({min: undefined, max: undefined}), total_users: faker.number.int({min: undefined, max: undefined}), total_optimizations: faker.number.int({min: undefined, max: undefined}), ...overrideResponse})

export const getGetOperatorsInfoOperatorsGetResponseMock = (): Operator[] => (faker.helpers.arrayElements(Object.values(Operator)))

export const getGetTariffsInfoTariffsGetResponseMock = (): Tariff[] => (faker.helpers.arrayElements(Object.values(Tariff)))

export const getGetTechnologiesInfoTechnologiesGetResponseMock = (): GetTechnologiesInfoTechnologiesGet200 => ({
        [faker.string.alphanumeric(5)]: {}
      })

export const getGetFuelsInfoFuelsGetResponseMock = (): GetFuelsInfoFuelsGet200 => ({
        [faker.string.alphanumeric(5)]: {}
      })

export const getGetThermoLevelsInfoThermoLevelsGetResponseMock = (): GetThermoLevelsInfoThermoLevelsGet200 => ({
        [faker.string.alphanumeric(5)]: {}
      })


export const getGetAppInfoInfoGetMockHandler = (overrideResponse?: AppInfoModel | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AppInfoModel> | AppInfoModel), options?: RequestHandlerOptions) => {
  return http.get('*/info', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetAppInfoInfoGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetOperatorsInfoOperatorsGetMockHandler = (overrideResponse?: Operator[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Operator[]> | Operator[]), options?: RequestHandlerOptions) => {
  return http.get('*/info/operators', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetOperatorsInfoOperatorsGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetTariffsInfoTariffsGetMockHandler = (overrideResponse?: Tariff[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Tariff[]> | Tariff[]), options?: RequestHandlerOptions) => {
  return http.get('*/info/tariffs', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetTariffsInfoTariffsGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetTechnologiesInfoTechnologiesGetMockHandler = (overrideResponse?: GetTechnologiesInfoTechnologiesGet200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetTechnologiesInfoTechnologiesGet200> | GetTechnologiesInfoTechnologiesGet200), options?: RequestHandlerOptions) => {
  return http.get('*/info/technologies', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetTechnologiesInfoTechnologiesGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetFuelsInfoFuelsGetMockHandler = (overrideResponse?: GetFuelsInfoFuelsGet200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetFuelsInfoFuelsGet200> | GetFuelsInfoFuelsGet200), options?: RequestHandlerOptions) => {
  return http.get('*/info/fuels', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetFuelsInfoFuelsGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetThermoLevelsInfoThermoLevelsGetMockHandler = (overrideResponse?: GetThermoLevelsInfoThermoLevelsGet200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetThermoLevelsInfoThermoLevelsGet200> | GetThermoLevelsInfoThermoLevelsGet200), options?: RequestHandlerOptions) => {
  return http.get('*/info/thermo_levels', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetThermoLevelsInfoThermoLevelsGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getInfoMock = () => [
  getGetAppInfoInfoGetMockHandler(),
  getGetOperatorsInfoOperatorsGetMockHandler(),
  getGetTariffsInfoTariffsGetMockHandler(),
  getGetTechnologiesInfoTechnologiesGetMockHandler(),
  getGetFuelsInfoFuelsGetMockHandler(),
  getGetThermoLevelsInfoThermoLevelsGetMockHandler()
]
