/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  AppInfoModel,
  GetFuelsInfoFuelsGet200,
  GetTechnologiesInfoTechnologiesGet200,
  GetThermoLevelsInfoThermoLevelsGet200,
  Operator,
  Tariff
} from '.././model';



  
  
  
/**
 * @summary Returns info about app
 */
export type getAppInfoInfoGetResponse200 = {
  data: AppInfoModel
  status: 200
}
    
export type getAppInfoInfoGetResponseSuccess = (getAppInfoInfoGetResponse200) & {
  headers: Headers;
};
;

export type getAppInfoInfoGetResponse = (getAppInfoInfoGetResponseSuccess)

export const getGetAppInfoInfoGetUrl = () => {


  

  return `/info`
}

export const getAppInfoInfoGet = async ( options?: RequestInit): Promise<getAppInfoInfoGetResponse> => {
  
  const res = await fetch(getGetAppInfoInfoGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAppInfoInfoGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAppInfoInfoGetResponse
}




export const getGetAppInfoInfoGetKey = () => [`/info`] as const;

export type GetAppInfoInfoGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAppInfoInfoGet>>>
export type GetAppInfoInfoGetQueryError = Promise<unknown>

/**
 * @summary Returns info about app
 */
export const useGetAppInfoInfoGet = <TError = Promise<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAppInfoInfoGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAppInfoInfoGetKey() : null);
  const swrFn = () => getAppInfoInfoGet(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Returns list of operators
 */
export type getOperatorsInfoOperatorsGetResponse200 = {
  data: Operator[]
  status: 200
}
    
export type getOperatorsInfoOperatorsGetResponseSuccess = (getOperatorsInfoOperatorsGetResponse200) & {
  headers: Headers;
};
;

export type getOperatorsInfoOperatorsGetResponse = (getOperatorsInfoOperatorsGetResponseSuccess)

export const getGetOperatorsInfoOperatorsGetUrl = () => {


  

  return `/info/operators`
}

export const getOperatorsInfoOperatorsGet = async ( options?: RequestInit): Promise<getOperatorsInfoOperatorsGetResponse> => {
  
  const res = await fetch(getGetOperatorsInfoOperatorsGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getOperatorsInfoOperatorsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getOperatorsInfoOperatorsGetResponse
}




export const getGetOperatorsInfoOperatorsGetKey = () => [`/info/operators`] as const;

export type GetOperatorsInfoOperatorsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getOperatorsInfoOperatorsGet>>>
export type GetOperatorsInfoOperatorsGetQueryError = Promise<unknown>

/**
 * @summary Returns list of operators
 */
export const useGetOperatorsInfoOperatorsGet = <TError = Promise<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getOperatorsInfoOperatorsGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetOperatorsInfoOperatorsGetKey() : null);
  const swrFn = () => getOperatorsInfoOperatorsGet(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Returns list of tariffs
 */
export type getTariffsInfoTariffsGetResponse200 = {
  data: Tariff[]
  status: 200
}
    
export type getTariffsInfoTariffsGetResponseSuccess = (getTariffsInfoTariffsGetResponse200) & {
  headers: Headers;
};
;

export type getTariffsInfoTariffsGetResponse = (getTariffsInfoTariffsGetResponseSuccess)

export const getGetTariffsInfoTariffsGetUrl = () => {


  

  return `/info/tariffs`
}

export const getTariffsInfoTariffsGet = async ( options?: RequestInit): Promise<getTariffsInfoTariffsGetResponse> => {
  
  const res = await fetch(getGetTariffsInfoTariffsGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getTariffsInfoTariffsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getTariffsInfoTariffsGetResponse
}




export const getGetTariffsInfoTariffsGetKey = () => [`/info/tariffs`] as const;

export type GetTariffsInfoTariffsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTariffsInfoTariffsGet>>>
export type GetTariffsInfoTariffsGetQueryError = Promise<unknown>

/**
 * @summary Returns list of tariffs
 */
export const useGetTariffsInfoTariffsGet = <TError = Promise<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getTariffsInfoTariffsGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetTariffsInfoTariffsGetKey() : null);
  const swrFn = () => getTariffsInfoTariffsGet(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Returns list of technologies
 */
export type getTechnologiesInfoTechnologiesGetResponse200 = {
  data: GetTechnologiesInfoTechnologiesGet200
  status: 200
}
    
export type getTechnologiesInfoTechnologiesGetResponseSuccess = (getTechnologiesInfoTechnologiesGetResponse200) & {
  headers: Headers;
};
;

export type getTechnologiesInfoTechnologiesGetResponse = (getTechnologiesInfoTechnologiesGetResponseSuccess)

export const getGetTechnologiesInfoTechnologiesGetUrl = () => {


  

  return `/info/technologies`
}

export const getTechnologiesInfoTechnologiesGet = async ( options?: RequestInit): Promise<getTechnologiesInfoTechnologiesGetResponse> => {
  
  const res = await fetch(getGetTechnologiesInfoTechnologiesGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getTechnologiesInfoTechnologiesGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getTechnologiesInfoTechnologiesGetResponse
}




export const getGetTechnologiesInfoTechnologiesGetKey = () => [`/info/technologies`] as const;

export type GetTechnologiesInfoTechnologiesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTechnologiesInfoTechnologiesGet>>>
export type GetTechnologiesInfoTechnologiesGetQueryError = Promise<unknown>

/**
 * @summary Returns list of technologies
 */
export const useGetTechnologiesInfoTechnologiesGet = <TError = Promise<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getTechnologiesInfoTechnologiesGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetTechnologiesInfoTechnologiesGetKey() : null);
  const swrFn = () => getTechnologiesInfoTechnologiesGet(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Returns list of fuels
 */
export type getFuelsInfoFuelsGetResponse200 = {
  data: GetFuelsInfoFuelsGet200
  status: 200
}
    
export type getFuelsInfoFuelsGetResponseSuccess = (getFuelsInfoFuelsGetResponse200) & {
  headers: Headers;
};
;

export type getFuelsInfoFuelsGetResponse = (getFuelsInfoFuelsGetResponseSuccess)

export const getGetFuelsInfoFuelsGetUrl = () => {


  

  return `/info/fuels`
}

export const getFuelsInfoFuelsGet = async ( options?: RequestInit): Promise<getFuelsInfoFuelsGetResponse> => {
  
  const res = await fetch(getGetFuelsInfoFuelsGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getFuelsInfoFuelsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getFuelsInfoFuelsGetResponse
}




export const getGetFuelsInfoFuelsGetKey = () => [`/info/fuels`] as const;

export type GetFuelsInfoFuelsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getFuelsInfoFuelsGet>>>
export type GetFuelsInfoFuelsGetQueryError = Promise<unknown>

/**
 * @summary Returns list of fuels
 */
export const useGetFuelsInfoFuelsGet = <TError = Promise<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getFuelsInfoFuelsGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetFuelsInfoFuelsGetKey() : null);
  const swrFn = () => getFuelsInfoFuelsGet(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Returns list of thermo levels for each building partition
 */
export type getThermoLevelsInfoThermoLevelsGetResponse200 = {
  data: GetThermoLevelsInfoThermoLevelsGet200
  status: 200
}
    
export type getThermoLevelsInfoThermoLevelsGetResponseSuccess = (getThermoLevelsInfoThermoLevelsGetResponse200) & {
  headers: Headers;
};
;

export type getThermoLevelsInfoThermoLevelsGetResponse = (getThermoLevelsInfoThermoLevelsGetResponseSuccess)

export const getGetThermoLevelsInfoThermoLevelsGetUrl = () => {


  

  return `/info/thermo_levels`
}

export const getThermoLevelsInfoThermoLevelsGet = async ( options?: RequestInit): Promise<getThermoLevelsInfoThermoLevelsGetResponse> => {
  
  const res = await fetch(getGetThermoLevelsInfoThermoLevelsGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getThermoLevelsInfoThermoLevelsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getThermoLevelsInfoThermoLevelsGetResponse
}




export const getGetThermoLevelsInfoThermoLevelsGetKey = () => [`/info/thermo_levels`] as const;

export type GetThermoLevelsInfoThermoLevelsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getThermoLevelsInfoThermoLevelsGet>>>
export type GetThermoLevelsInfoThermoLevelsGetQueryError = Promise<unknown>

/**
 * @summary Returns list of thermo levels for each building partition
 */
export const useGetThermoLevelsInfoThermoLevelsGet = <TError = Promise<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getThermoLevelsInfoThermoLevelsGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetThermoLevelsInfoThermoLevelsGetKey() : null);
  const swrFn = () => getThermoLevelsInfoThermoLevelsGet(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
