/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  BodyCloneOptimizationOptimizationOptIdClonePost,
  BodyUpdateOptimizationNameOptimizationOptIdNamePut,
  HTTPValidationError,
  OptimizationResponse,
  StateResponse
} from '.././model';



  
  
  
/**
 * @summary Creates a new optimization and returns its id
 */
export const createOptimizationOptimizationPost = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<number>> => {
    return axios.post(
      `/optimization`,undefined,options
    );
  }



export const getCreateOptimizationOptimizationPostMutationFetcher = ( options?: AxiosRequestConfig) => {
  return (_: Key, __: { arg: Arguments }) => {
    return createOptimizationOptimizationPost(options);
  }
}
export const getCreateOptimizationOptimizationPostMutationKey = () => [`/optimization`] as const;

export type CreateOptimizationOptimizationPostMutationResult = NonNullable<Awaited<ReturnType<typeof createOptimizationOptimizationPost>>>
export type CreateOptimizationOptimizationPostMutationError = AxiosError<unknown>

/**
 * @summary Creates a new optimization and returns its id
 */
export const useCreateOptimizationOptimizationPost = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createOptimizationOptimizationPost>>, TError, Key, Arguments, Awaited<ReturnType<typeof createOptimizationOptimizationPost>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateOptimizationOptimizationPostMutationKey();
  const swrFn = getCreateOptimizationOptimizationPostMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Updates the name of the optimization
 */
export const updateOptimizationNameOptimizationOptIdNamePut = (
    optId: number,
    bodyUpdateOptimizationNameOptimizationOptIdNamePut: BodyUpdateOptimizationNameOptimizationOptIdNamePut, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StateResponse>> => {
    return axios.put(
      `/optimization/${optId}/name`,
      bodyUpdateOptimizationNameOptimizationOptIdNamePut,options
    );
  }



export const getUpdateOptimizationNameOptimizationOptIdNamePutMutationFetcher = (optId: number, options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: BodyUpdateOptimizationNameOptimizationOptIdNamePut }) => {
    return updateOptimizationNameOptimizationOptIdNamePut(optId, arg, options);
  }
}
export const getUpdateOptimizationNameOptimizationOptIdNamePutMutationKey = (optId: number,) => [`/optimization/${optId}/name`] as const;

export type UpdateOptimizationNameOptimizationOptIdNamePutMutationResult = NonNullable<Awaited<ReturnType<typeof updateOptimizationNameOptimizationOptIdNamePut>>>
export type UpdateOptimizationNameOptimizationOptIdNamePutMutationError = AxiosError<HTTPValidationError>

/**
 * @summary Updates the name of the optimization
 */
export const useUpdateOptimizationNameOptimizationOptIdNamePut = <TError = AxiosError<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateOptimizationNameOptimizationOptIdNamePut>>, TError, Key, BodyUpdateOptimizationNameOptimizationOptIdNamePut, Awaited<ReturnType<typeof updateOptimizationNameOptimizationOptIdNamePut>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateOptimizationNameOptimizationOptIdNamePutMutationKey(optId);
  const swrFn = getUpdateOptimizationNameOptimizationOptIdNamePutMutationFetcher(optId, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Returns all optimizations
 */
export const getAllOptimizationsOptimizationAllGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OptimizationResponse[]>> => {
    return axios.get(
      `/optimization/all`,options
    );
  }



export const getGetAllOptimizationsOptimizationAllGetKey = () => [`/optimization/all`] as const;

export type GetAllOptimizationsOptimizationAllGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAllOptimizationsOptimizationAllGet>>>
export type GetAllOptimizationsOptimizationAllGetQueryError = AxiosError<unknown>

/**
 * @summary Returns all optimizations
 */
export const useGetAllOptimizationsOptimizationAllGet = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAllOptimizationsOptimizationAllGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAllOptimizationsOptimizationAllGetKey() : null);
  const swrFn = () => getAllOptimizationsOptimizationAllGet(axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Returns single optimization by id
 */
export const getOptimizationOptimizationOptIdGet = (
    optId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OptimizationResponse>> => {
    return axios.get(
      `/optimization/${optId}`,options
    );
  }



export const getGetOptimizationOptimizationOptIdGetKey = (optId: number,) => [`/optimization/${optId}`] as const;

export type GetOptimizationOptimizationOptIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getOptimizationOptimizationOptIdGet>>>
export type GetOptimizationOptimizationOptIdGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Returns single optimization by id
 */
export const useGetOptimizationOptimizationOptIdGet = <TError = AxiosError<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getOptimizationOptimizationOptIdGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(optId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetOptimizationOptimizationOptIdGetKey(optId) : null);
  const swrFn = () => getOptimizationOptimizationOptIdGet(optId, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Deletes the optimization by id
 */
export const deleteOptimizationOptimizationOptIdDelete = (
    optId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axios.delete(
      `/optimization/${optId}`,options
    );
  }



export const getDeleteOptimizationOptimizationOptIdDeleteMutationFetcher = (optId: number, options?: AxiosRequestConfig) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteOptimizationOptimizationOptIdDelete(optId, options);
  }
}
export const getDeleteOptimizationOptimizationOptIdDeleteMutationKey = (optId: number,) => [`/optimization/${optId}`] as const;

export type DeleteOptimizationOptimizationOptIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOptimizationOptimizationOptIdDelete>>>
export type DeleteOptimizationOptimizationOptIdDeleteMutationError = AxiosError<HTTPValidationError>

/**
 * @summary Deletes the optimization by id
 */
export const useDeleteOptimizationOptimizationOptIdDelete = <TError = AxiosError<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteOptimizationOptimizationOptIdDelete>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteOptimizationOptimizationOptIdDelete>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteOptimizationOptimizationOptIdDeleteMutationKey(optId);
  const swrFn = getDeleteOptimizationOptimizationOptIdDeleteMutationFetcher(optId, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Confirms the optimization by id
 */
export const confirmOptimizationOptimizationOptIdConfirmGet = (
    optId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StateResponse>> => {
    return axios.get(
      `/optimization/${optId}/confirm`,options
    );
  }



export const getConfirmOptimizationOptimizationOptIdConfirmGetKey = (optId: number,) => [`/optimization/${optId}/confirm`] as const;

export type ConfirmOptimizationOptimizationOptIdConfirmGetQueryResult = NonNullable<Awaited<ReturnType<typeof confirmOptimizationOptimizationOptIdConfirmGet>>>
export type ConfirmOptimizationOptimizationOptIdConfirmGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Confirms the optimization by id
 */
export const useConfirmOptimizationOptimizationOptIdConfirmGet = <TError = AxiosError<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof confirmOptimizationOptimizationOptIdConfirmGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(optId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getConfirmOptimizationOptimizationOptIdConfirmGetKey(optId) : null);
  const swrFn = () => confirmOptimizationOptimizationOptIdConfirmGet(optId, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Clones the optimization by id
 */
export const cloneOptimizationOptimizationOptIdClonePost = (
    optId: number,
    bodyCloneOptimizationOptimizationOptIdClonePost: BodyCloneOptimizationOptimizationOptIdClonePost, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<number>> => {
    return axios.post(
      `/optimization/${optId}/clone`,
      bodyCloneOptimizationOptimizationOptIdClonePost,options
    );
  }



export const getCloneOptimizationOptimizationOptIdClonePostMutationFetcher = (optId: number, options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: BodyCloneOptimizationOptimizationOptIdClonePost }) => {
    return cloneOptimizationOptimizationOptIdClonePost(optId, arg, options);
  }
}
export const getCloneOptimizationOptimizationOptIdClonePostMutationKey = (optId: number,) => [`/optimization/${optId}/clone`] as const;

export type CloneOptimizationOptimizationOptIdClonePostMutationResult = NonNullable<Awaited<ReturnType<typeof cloneOptimizationOptimizationOptIdClonePost>>>
export type CloneOptimizationOptimizationOptIdClonePostMutationError = AxiosError<HTTPValidationError>

/**
 * @summary Clones the optimization by id
 */
export const useCloneOptimizationOptimizationOptIdClonePost = <TError = AxiosError<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof cloneOptimizationOptimizationOptIdClonePost>>, TError, Key, BodyCloneOptimizationOptimizationOptIdClonePost, Awaited<ReturnType<typeof cloneOptimizationOptimizationOptIdClonePost>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCloneOptimizationOptimizationOptIdClonePostMutationKey(optId);
  const swrFn = getCloneOptimizationOptimizationOptIdClonePostMutationFetcher(optId, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
