/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  OptimizationResponse,
  StateResponse
} from '.././model';


export const getCreateOptimizationOptimizationPostResponseMock = (): number => (faker.number.int())

export const getUpdateOptimizationNameOptimizationOptIdNamePutResponseMock = (): StateResponse => (faker.helpers.arrayElement(['SUCCESS','ERROR'] as const))

export const getGetAllOptimizationsOptimizationAllGetResponseMock = (): OptimizationResponse[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.number.int({min: undefined, max: undefined}), status: faker.string.alpha({length: {min: 10, max: 20}}), queue_position: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null,]), update_time: `${faker.date.past().toISOString().split('.')[0]}Z`, address_point_id: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null,]), location_data: faker.helpers.arrayElement([{voivodeship: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), voivodeship_id: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null,]), city: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), city_id: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null,]), street: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), street_id: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null,]), house_number: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,])},null,]), name: faker.string.alpha({length: {min: 10, max: 20}})})))

export const getGetOptimizationOptimizationOptIdGetResponseMock = (overrideResponse: Partial< OptimizationResponse > = {}): OptimizationResponse => ({id: faker.number.int({min: undefined, max: undefined}), status: faker.string.alpha({length: {min: 10, max: 20}}), queue_position: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null,]), update_time: `${faker.date.past().toISOString().split('.')[0]}Z`, address_point_id: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null,]), location_data: faker.helpers.arrayElement([{voivodeship: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), voivodeship_id: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null,]), city: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), city_id: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null,]), street: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), street_id: faker.helpers.arrayElement([faker.number.int({min: undefined, max: undefined}),null,]), house_number: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,])},null,]), name: faker.string.alpha({length: {min: 10, max: 20}}), ...overrideResponse})

export const getConfirmOptimizationOptimizationOptIdConfirmGetResponseMock = (): StateResponse => (faker.helpers.arrayElement(['SUCCESS','ERROR'] as const))

export const getCloneOptimizationOptimizationOptIdClonePostResponseMock = (): number => (faker.number.int())


export const getCreateOptimizationOptimizationPostMockHandler = (overrideResponse?: number | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<number> | number), options?: RequestHandlerOptions) => {
  return http.post('*/optimization', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateOptimizationOptimizationPostResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateOptimizationNameOptimizationOptIdNamePutMockHandler = (overrideResponse?: StateResponse | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<StateResponse> | StateResponse), options?: RequestHandlerOptions) => {
  return http.put('*/optimization/:optId/name', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateOptimizationNameOptimizationOptIdNamePutResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetAllOptimizationsOptimizationAllGetMockHandler = (overrideResponse?: OptimizationResponse[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<OptimizationResponse[]> | OptimizationResponse[]), options?: RequestHandlerOptions) => {
  return http.get('*/optimization/all', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetAllOptimizationsOptimizationAllGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetOptimizationOptimizationOptIdGetMockHandler = (overrideResponse?: OptimizationResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<OptimizationResponse> | OptimizationResponse), options?: RequestHandlerOptions) => {
  return http.get('*/optimization/:optId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetOptimizationOptimizationOptIdGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeleteOptimizationOptimizationOptIdDeleteMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/optimization/:optId', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 204,
        
      })
  }, options)
}

export const getConfirmOptimizationOptimizationOptIdConfirmGetMockHandler = (overrideResponse?: StateResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<StateResponse> | StateResponse), options?: RequestHandlerOptions) => {
  return http.get('*/optimization/:optId/confirm', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getConfirmOptimizationOptimizationOptIdConfirmGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getCloneOptimizationOptimizationOptIdClonePostMockHandler = (overrideResponse?: number | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<number> | number), options?: RequestHandlerOptions) => {
  return http.post('*/optimization/:optId/clone', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCloneOptimizationOptimizationOptIdClonePostResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getOptimizationMock = () => [
  getCreateOptimizationOptimizationPostMockHandler(),
  getUpdateOptimizationNameOptimizationOptIdNamePutMockHandler(),
  getGetAllOptimizationsOptimizationAllGetMockHandler(),
  getGetOptimizationOptimizationOptIdGetMockHandler(),
  getDeleteOptimizationOptimizationOptIdDeleteMockHandler(),
  getConfirmOptimizationOptimizationOptIdConfirmGetMockHandler(),
  getCloneOptimizationOptimizationOptIdClonePostMockHandler()
]
