/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  BodyCloneOptimizationOptimizationOptIdClonePost,
  BodyUpdateOptimizationNameOptimizationOptIdNamePut,
  HTTPValidationError,
  OptimizationResponse,
  StateResponse
} from '.././model';



  
  
  
/**
 * @summary Creates a new optimization and returns its id
 */
export type createOptimizationOptimizationPostResponse201 = {
  data: number
  status: 201
}
    
export type createOptimizationOptimizationPostResponseSuccess = (createOptimizationOptimizationPostResponse201) & {
  headers: Headers;
};
;

export type createOptimizationOptimizationPostResponse = (createOptimizationOptimizationPostResponseSuccess)

export const getCreateOptimizationOptimizationPostUrl = () => {


  

  return `/optimization`
}

export const createOptimizationOptimizationPost = async ( options?: RequestInit): Promise<createOptimizationOptimizationPostResponse> => {
  
  const res = await fetch(getCreateOptimizationOptimizationPostUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createOptimizationOptimizationPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createOptimizationOptimizationPostResponse
}




export const getCreateOptimizationOptimizationPostMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return createOptimizationOptimizationPost(options);
  }
}
export const getCreateOptimizationOptimizationPostMutationKey = () => [`/optimization`] as const;

export type CreateOptimizationOptimizationPostMutationResult = NonNullable<Awaited<ReturnType<typeof createOptimizationOptimizationPost>>>
export type CreateOptimizationOptimizationPostMutationError = Promise<unknown>

/**
 * @summary Creates a new optimization and returns its id
 */
export const useCreateOptimizationOptimizationPost = <TError = Promise<unknown>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createOptimizationOptimizationPost>>, TError, Key, Arguments, Awaited<ReturnType<typeof createOptimizationOptimizationPost>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateOptimizationOptimizationPostMutationKey();
  const swrFn = getCreateOptimizationOptimizationPostMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Updates the name of the optimization
 */
export type updateOptimizationNameOptimizationOptIdNamePutResponse200 = {
  data: StateResponse
  status: 200
}

export type updateOptimizationNameOptimizationOptIdNamePutResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type updateOptimizationNameOptimizationOptIdNamePutResponseSuccess = (updateOptimizationNameOptimizationOptIdNamePutResponse200) & {
  headers: Headers;
};
export type updateOptimizationNameOptimizationOptIdNamePutResponseError = (updateOptimizationNameOptimizationOptIdNamePutResponse422) & {
  headers: Headers;
};

export type updateOptimizationNameOptimizationOptIdNamePutResponse = (updateOptimizationNameOptimizationOptIdNamePutResponseSuccess | updateOptimizationNameOptimizationOptIdNamePutResponseError)

export const getUpdateOptimizationNameOptimizationOptIdNamePutUrl = (optId: number,) => {


  

  return `/optimization/${optId}/name`
}

export const updateOptimizationNameOptimizationOptIdNamePut = async (optId: number,
    bodyUpdateOptimizationNameOptimizationOptIdNamePut: BodyUpdateOptimizationNameOptimizationOptIdNamePut, options?: RequestInit): Promise<updateOptimizationNameOptimizationOptIdNamePutResponse> => {
  
  const res = await fetch(getUpdateOptimizationNameOptimizationOptIdNamePutUrl(optId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bodyUpdateOptimizationNameOptimizationOptIdNamePut,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateOptimizationNameOptimizationOptIdNamePutResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateOptimizationNameOptimizationOptIdNamePutResponse
}




export const getUpdateOptimizationNameOptimizationOptIdNamePutMutationFetcher = (optId: number, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: BodyUpdateOptimizationNameOptimizationOptIdNamePut }) => {
    return updateOptimizationNameOptimizationOptIdNamePut(optId, arg, options);
  }
}
export const getUpdateOptimizationNameOptimizationOptIdNamePutMutationKey = (optId: number,) => [`/optimization/${optId}/name`] as const;

export type UpdateOptimizationNameOptimizationOptIdNamePutMutationResult = NonNullable<Awaited<ReturnType<typeof updateOptimizationNameOptimizationOptIdNamePut>>>
export type UpdateOptimizationNameOptimizationOptIdNamePutMutationError = Promise<HTTPValidationError>

/**
 * @summary Updates the name of the optimization
 */
export const useUpdateOptimizationNameOptimizationOptIdNamePut = <TError = Promise<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateOptimizationNameOptimizationOptIdNamePut>>, TError, Key, BodyUpdateOptimizationNameOptimizationOptIdNamePut, Awaited<ReturnType<typeof updateOptimizationNameOptimizationOptIdNamePut>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateOptimizationNameOptimizationOptIdNamePutMutationKey(optId);
  const swrFn = getUpdateOptimizationNameOptimizationOptIdNamePutMutationFetcher(optId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Returns all optimizations
 */
export type getAllOptimizationsOptimizationAllGetResponse200 = {
  data: OptimizationResponse[]
  status: 200
}
    
export type getAllOptimizationsOptimizationAllGetResponseSuccess = (getAllOptimizationsOptimizationAllGetResponse200) & {
  headers: Headers;
};
;

export type getAllOptimizationsOptimizationAllGetResponse = (getAllOptimizationsOptimizationAllGetResponseSuccess)

export const getGetAllOptimizationsOptimizationAllGetUrl = () => {


  

  return `/optimization/all`
}

export const getAllOptimizationsOptimizationAllGet = async ( options?: RequestInit): Promise<getAllOptimizationsOptimizationAllGetResponse> => {
  
  const res = await fetch(getGetAllOptimizationsOptimizationAllGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllOptimizationsOptimizationAllGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllOptimizationsOptimizationAllGetResponse
}




export const getGetAllOptimizationsOptimizationAllGetKey = () => [`/optimization/all`] as const;

export type GetAllOptimizationsOptimizationAllGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAllOptimizationsOptimizationAllGet>>>
export type GetAllOptimizationsOptimizationAllGetQueryError = Promise<unknown>

/**
 * @summary Returns all optimizations
 */
export const useGetAllOptimizationsOptimizationAllGet = <TError = Promise<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAllOptimizationsOptimizationAllGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAllOptimizationsOptimizationAllGetKey() : null);
  const swrFn = () => getAllOptimizationsOptimizationAllGet(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Returns single optimization by id
 */
export type getOptimizationOptimizationOptIdGetResponse200 = {
  data: OptimizationResponse
  status: 200
}

export type getOptimizationOptimizationOptIdGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getOptimizationOptimizationOptIdGetResponseSuccess = (getOptimizationOptimizationOptIdGetResponse200) & {
  headers: Headers;
};
export type getOptimizationOptimizationOptIdGetResponseError = (getOptimizationOptimizationOptIdGetResponse422) & {
  headers: Headers;
};

export type getOptimizationOptimizationOptIdGetResponse = (getOptimizationOptimizationOptIdGetResponseSuccess | getOptimizationOptimizationOptIdGetResponseError)

export const getGetOptimizationOptimizationOptIdGetUrl = (optId: number,) => {


  

  return `/optimization/${optId}`
}

export const getOptimizationOptimizationOptIdGet = async (optId: number, options?: RequestInit): Promise<getOptimizationOptimizationOptIdGetResponse> => {
  
  const res = await fetch(getGetOptimizationOptimizationOptIdGetUrl(optId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getOptimizationOptimizationOptIdGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getOptimizationOptimizationOptIdGetResponse
}




export const getGetOptimizationOptimizationOptIdGetKey = (optId: number,) => [`/optimization/${optId}`] as const;

export type GetOptimizationOptimizationOptIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getOptimizationOptimizationOptIdGet>>>
export type GetOptimizationOptimizationOptIdGetQueryError = Promise<HTTPValidationError>

/**
 * @summary Returns single optimization by id
 */
export const useGetOptimizationOptimizationOptIdGet = <TError = Promise<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getOptimizationOptimizationOptIdGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(optId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetOptimizationOptimizationOptIdGetKey(optId) : null);
  const swrFn = () => getOptimizationOptimizationOptIdGet(optId, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Deletes the optimization by id
 */
export type deleteOptimizationOptimizationOptIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteOptimizationOptimizationOptIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type deleteOptimizationOptimizationOptIdDeleteResponseSuccess = (deleteOptimizationOptimizationOptIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteOptimizationOptimizationOptIdDeleteResponseError = (deleteOptimizationOptimizationOptIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteOptimizationOptimizationOptIdDeleteResponse = (deleteOptimizationOptimizationOptIdDeleteResponseSuccess | deleteOptimizationOptimizationOptIdDeleteResponseError)

export const getDeleteOptimizationOptimizationOptIdDeleteUrl = (optId: number,) => {


  

  return `/optimization/${optId}`
}

export const deleteOptimizationOptimizationOptIdDelete = async (optId: number, options?: RequestInit): Promise<deleteOptimizationOptimizationOptIdDeleteResponse> => {
  
  const res = await fetch(getDeleteOptimizationOptimizationOptIdDeleteUrl(optId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteOptimizationOptimizationOptIdDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteOptimizationOptimizationOptIdDeleteResponse
}




export const getDeleteOptimizationOptimizationOptIdDeleteMutationFetcher = (optId: number, options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteOptimizationOptimizationOptIdDelete(optId, options);
  }
}
export const getDeleteOptimizationOptimizationOptIdDeleteMutationKey = (optId: number,) => [`/optimization/${optId}`] as const;

export type DeleteOptimizationOptimizationOptIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOptimizationOptimizationOptIdDelete>>>
export type DeleteOptimizationOptimizationOptIdDeleteMutationError = Promise<HTTPValidationError>

/**
 * @summary Deletes the optimization by id
 */
export const useDeleteOptimizationOptimizationOptIdDelete = <TError = Promise<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteOptimizationOptimizationOptIdDelete>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteOptimizationOptimizationOptIdDelete>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteOptimizationOptimizationOptIdDeleteMutationKey(optId);
  const swrFn = getDeleteOptimizationOptimizationOptIdDeleteMutationFetcher(optId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Confirms the optimization by id
 */
export type confirmOptimizationOptimizationOptIdConfirmGetResponse200 = {
  data: StateResponse
  status: 200
}

export type confirmOptimizationOptimizationOptIdConfirmGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type confirmOptimizationOptimizationOptIdConfirmGetResponseSuccess = (confirmOptimizationOptimizationOptIdConfirmGetResponse200) & {
  headers: Headers;
};
export type confirmOptimizationOptimizationOptIdConfirmGetResponseError = (confirmOptimizationOptimizationOptIdConfirmGetResponse422) & {
  headers: Headers;
};

export type confirmOptimizationOptimizationOptIdConfirmGetResponse = (confirmOptimizationOptimizationOptIdConfirmGetResponseSuccess | confirmOptimizationOptimizationOptIdConfirmGetResponseError)

export const getConfirmOptimizationOptimizationOptIdConfirmGetUrl = (optId: number,) => {


  

  return `/optimization/${optId}/confirm`
}

export const confirmOptimizationOptimizationOptIdConfirmGet = async (optId: number, options?: RequestInit): Promise<confirmOptimizationOptimizationOptIdConfirmGetResponse> => {
  
  const res = await fetch(getConfirmOptimizationOptimizationOptIdConfirmGetUrl(optId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: confirmOptimizationOptimizationOptIdConfirmGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as confirmOptimizationOptimizationOptIdConfirmGetResponse
}




export const getConfirmOptimizationOptimizationOptIdConfirmGetKey = (optId: number,) => [`/optimization/${optId}/confirm`] as const;

export type ConfirmOptimizationOptimizationOptIdConfirmGetQueryResult = NonNullable<Awaited<ReturnType<typeof confirmOptimizationOptimizationOptIdConfirmGet>>>
export type ConfirmOptimizationOptimizationOptIdConfirmGetQueryError = Promise<HTTPValidationError>

/**
 * @summary Confirms the optimization by id
 */
export const useConfirmOptimizationOptimizationOptIdConfirmGet = <TError = Promise<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof confirmOptimizationOptimizationOptIdConfirmGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(optId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getConfirmOptimizationOptimizationOptIdConfirmGetKey(optId) : null);
  const swrFn = () => confirmOptimizationOptimizationOptIdConfirmGet(optId, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Clones the optimization by id
 */
export type cloneOptimizationOptimizationOptIdClonePostResponse201 = {
  data: number
  status: 201
}

export type cloneOptimizationOptimizationOptIdClonePostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type cloneOptimizationOptimizationOptIdClonePostResponseSuccess = (cloneOptimizationOptimizationOptIdClonePostResponse201) & {
  headers: Headers;
};
export type cloneOptimizationOptimizationOptIdClonePostResponseError = (cloneOptimizationOptimizationOptIdClonePostResponse422) & {
  headers: Headers;
};

export type cloneOptimizationOptimizationOptIdClonePostResponse = (cloneOptimizationOptimizationOptIdClonePostResponseSuccess | cloneOptimizationOptimizationOptIdClonePostResponseError)

export const getCloneOptimizationOptimizationOptIdClonePostUrl = (optId: number,) => {


  

  return `/optimization/${optId}/clone`
}

export const cloneOptimizationOptimizationOptIdClonePost = async (optId: number,
    bodyCloneOptimizationOptimizationOptIdClonePost: BodyCloneOptimizationOptimizationOptIdClonePost, options?: RequestInit): Promise<cloneOptimizationOptimizationOptIdClonePostResponse> => {
  
  const res = await fetch(getCloneOptimizationOptimizationOptIdClonePostUrl(optId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bodyCloneOptimizationOptimizationOptIdClonePost,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: cloneOptimizationOptimizationOptIdClonePostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as cloneOptimizationOptimizationOptIdClonePostResponse
}




export const getCloneOptimizationOptimizationOptIdClonePostMutationFetcher = (optId: number, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: BodyCloneOptimizationOptimizationOptIdClonePost }) => {
    return cloneOptimizationOptimizationOptIdClonePost(optId, arg, options);
  }
}
export const getCloneOptimizationOptimizationOptIdClonePostMutationKey = (optId: number,) => [`/optimization/${optId}/clone`] as const;

export type CloneOptimizationOptimizationOptIdClonePostMutationResult = NonNullable<Awaited<ReturnType<typeof cloneOptimizationOptimizationOptIdClonePost>>>
export type CloneOptimizationOptimizationOptIdClonePostMutationError = Promise<HTTPValidationError>

/**
 * @summary Clones the optimization by id
 */
export const useCloneOptimizationOptimizationOptIdClonePost = <TError = Promise<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof cloneOptimizationOptimizationOptIdClonePost>>, TError, Key, BodyCloneOptimizationOptimizationOptIdClonePost, Awaited<ReturnType<typeof cloneOptimizationOptimizationOptIdClonePost>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCloneOptimizationOptimizationOptIdClonePostMutationKey(optId);
  const swrFn = getCloneOptimizationOptimizationOptIdClonePostMutationFetcher(optId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
