/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  AutocompleteAddressData,
  GetAddressDataAddressDataGetAddressDataGet200,
  GetAddressDataAddressDataGetAddressDataGetParams,
  GetAddressPointNamesAddressDataAutocompleteAddressPointGetParams,
  GetCityNamesAddressDataAutocompleteCityGetParams,
  GetStreetNamesAddressDataAutocompleteStreetGetParams,
  GetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetParams,
  HTTPValidationError
} from '.././model';



  
  
  
/**
 * Returns voivodeship names that match the query
 * @summary Get Voivodeship Names
 */
export const getVoivodeshipNamesAddressDataAutocompleteVoivodeshipGet = (
    params?: GetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AutocompleteAddressData[]>> => {
    return axios.get(
      `/address_data/autocomplete/voivodeship`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getGetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetKey = (params?: GetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetParams,) => [`/address_data/autocomplete/voivodeship`, ...(params ? [params]: [])] as const;

export type GetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetQueryResult = NonNullable<Awaited<ReturnType<typeof getVoivodeshipNamesAddressDataAutocompleteVoivodeshipGet>>>
export type GetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get Voivodeship Names
 */
export const useGetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGet = <TError = AxiosError<HTTPValidationError>>(
  params?: GetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getVoivodeshipNamesAddressDataAutocompleteVoivodeshipGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetKey(params) : null);
  const swrFn = () => getVoivodeshipNamesAddressDataAutocompleteVoivodeshipGet(params, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Returns city names that match the query
 * @summary Get City Names
 */
export const getCityNamesAddressDataAutocompleteCityGet = (
    params: GetCityNamesAddressDataAutocompleteCityGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AutocompleteAddressData[]>> => {
    return axios.get(
      `/address_data/autocomplete/city`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getGetCityNamesAddressDataAutocompleteCityGetKey = (params: GetCityNamesAddressDataAutocompleteCityGetParams,) => [`/address_data/autocomplete/city`, ...(params ? [params]: [])] as const;

export type GetCityNamesAddressDataAutocompleteCityGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCityNamesAddressDataAutocompleteCityGet>>>
export type GetCityNamesAddressDataAutocompleteCityGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get City Names
 */
export const useGetCityNamesAddressDataAutocompleteCityGet = <TError = AxiosError<HTTPValidationError>>(
  params: GetCityNamesAddressDataAutocompleteCityGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getCityNamesAddressDataAutocompleteCityGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetCityNamesAddressDataAutocompleteCityGetKey(params) : null);
  const swrFn = () => getCityNamesAddressDataAutocompleteCityGet(params, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Returns street names that match the query
 * @summary Get Street Names
 */
export const getStreetNamesAddressDataAutocompleteStreetGet = (
    params: GetStreetNamesAddressDataAutocompleteStreetGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AutocompleteAddressData[]>> => {
    return axios.get(
      `/address_data/autocomplete/street`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getGetStreetNamesAddressDataAutocompleteStreetGetKey = (params: GetStreetNamesAddressDataAutocompleteStreetGetParams,) => [`/address_data/autocomplete/street`, ...(params ? [params]: [])] as const;

export type GetStreetNamesAddressDataAutocompleteStreetGetQueryResult = NonNullable<Awaited<ReturnType<typeof getStreetNamesAddressDataAutocompleteStreetGet>>>
export type GetStreetNamesAddressDataAutocompleteStreetGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get Street Names
 */
export const useGetStreetNamesAddressDataAutocompleteStreetGet = <TError = AxiosError<HTTPValidationError>>(
  params: GetStreetNamesAddressDataAutocompleteStreetGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getStreetNamesAddressDataAutocompleteStreetGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetStreetNamesAddressDataAutocompleteStreetGetKey(params) : null);
  const swrFn = () => getStreetNamesAddressDataAutocompleteStreetGet(params, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Returns address point house numbers that match the query
 * @summary Get Address Point Names
 */
export const getAddressPointNamesAddressDataAutocompleteAddressPointGet = (
    params: GetAddressPointNamesAddressDataAutocompleteAddressPointGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AutocompleteAddressData[]>> => {
    return axios.get(
      `/address_data/autocomplete/address_point`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getGetAddressPointNamesAddressDataAutocompleteAddressPointGetKey = (params: GetAddressPointNamesAddressDataAutocompleteAddressPointGetParams,) => [`/address_data/autocomplete/address_point`, ...(params ? [params]: [])] as const;

export type GetAddressPointNamesAddressDataAutocompleteAddressPointGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAddressPointNamesAddressDataAutocompleteAddressPointGet>>>
export type GetAddressPointNamesAddressDataAutocompleteAddressPointGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get Address Point Names
 */
export const useGetAddressPointNamesAddressDataAutocompleteAddressPointGet = <TError = AxiosError<HTTPValidationError>>(
  params: GetAddressPointNamesAddressDataAutocompleteAddressPointGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAddressPointNamesAddressDataAutocompleteAddressPointGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAddressPointNamesAddressDataAutocompleteAddressPointGetKey(params) : null);
  const swrFn = () => getAddressPointNamesAddressDataAutocompleteAddressPointGet(params, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Returns data about building at given address point
 * @summary Get Address Data
 */
export const getAddressDataAddressDataGetAddressDataGet = (
    params: GetAddressDataAddressDataGetAddressDataGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetAddressDataAddressDataGetAddressDataGet200>> => {
    return axios.get(
      `/address_data/get_address_data`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getGetAddressDataAddressDataGetAddressDataGetKey = (params: GetAddressDataAddressDataGetAddressDataGetParams,) => [`/address_data/get_address_data`, ...(params ? [params]: [])] as const;

export type GetAddressDataAddressDataGetAddressDataGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAddressDataAddressDataGetAddressDataGet>>>
export type GetAddressDataAddressDataGetAddressDataGetQueryError = AxiosError<void | HTTPValidationError>

/**
 * @summary Get Address Data
 */
export const useGetAddressDataAddressDataGetAddressDataGet = <TError = AxiosError<void | HTTPValidationError>>(
  params: GetAddressDataAddressDataGetAddressDataGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAddressDataAddressDataGetAddressDataGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAddressDataAddressDataGetAddressDataGetKey(params) : null);
  const swrFn = () => getAddressDataAddressDataGetAddressDataGet(params, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
