/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  AutocompleteAddressData,
  GetAddressDataAddressDataGetAddressDataGet200
} from '.././model';


export const getGetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetResponseMock = (): AutocompleteAddressData[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.number.int({min: undefined, max: undefined}), value: faker.string.alpha({length: {min: 10, max: 20}})})))

export const getGetCityNamesAddressDataAutocompleteCityGetResponseMock = (): AutocompleteAddressData[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.number.int({min: undefined, max: undefined}), value: faker.string.alpha({length: {min: 10, max: 20}})})))

export const getGetStreetNamesAddressDataAutocompleteStreetGetResponseMock = (): AutocompleteAddressData[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.number.int({min: undefined, max: undefined}), value: faker.string.alpha({length: {min: 10, max: 20}})})))

export const getGetAddressPointNamesAddressDataAutocompleteAddressPointGetResponseMock = (): AutocompleteAddressData[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({id: faker.number.int({min: undefined, max: undefined}), value: faker.string.alpha({length: {min: 10, max: 20}})})))

export const getGetAddressDataAddressDataGetAddressDataGetResponseMock = (): GetAddressDataAddressDataGetAddressDataGet200 => ({})


export const getGetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetMockHandler = (overrideResponse?: AutocompleteAddressData[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AutocompleteAddressData[]> | AutocompleteAddressData[]), options?: RequestHandlerOptions) => {
  return http.get('*/address_data/autocomplete/voivodeship', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetCityNamesAddressDataAutocompleteCityGetMockHandler = (overrideResponse?: AutocompleteAddressData[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AutocompleteAddressData[]> | AutocompleteAddressData[]), options?: RequestHandlerOptions) => {
  return http.get('*/address_data/autocomplete/city', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetCityNamesAddressDataAutocompleteCityGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetStreetNamesAddressDataAutocompleteStreetGetMockHandler = (overrideResponse?: AutocompleteAddressData[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AutocompleteAddressData[]> | AutocompleteAddressData[]), options?: RequestHandlerOptions) => {
  return http.get('*/address_data/autocomplete/street', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetStreetNamesAddressDataAutocompleteStreetGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetAddressPointNamesAddressDataAutocompleteAddressPointGetMockHandler = (overrideResponse?: AutocompleteAddressData[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<AutocompleteAddressData[]> | AutocompleteAddressData[]), options?: RequestHandlerOptions) => {
  return http.get('*/address_data/autocomplete/address_point', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetAddressPointNamesAddressDataAutocompleteAddressPointGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetAddressDataAddressDataGetAddressDataGetMockHandler = (overrideResponse?: GetAddressDataAddressDataGetAddressDataGet200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetAddressDataAddressDataGetAddressDataGet200> | GetAddressDataAddressDataGetAddressDataGet200), options?: RequestHandlerOptions) => {
  return http.get('*/address_data/get_address_data', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetAddressDataAddressDataGetAddressDataGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getAddressDataMock = () => [
  getGetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetMockHandler(),
  getGetCityNamesAddressDataAutocompleteCityGetMockHandler(),
  getGetStreetNamesAddressDataAutocompleteStreetGetMockHandler(),
  getGetAddressPointNamesAddressDataAutocompleteAddressPointGetMockHandler(),
  getGetAddressDataAddressDataGetAddressDataGetMockHandler()
]
