/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  AutocompleteAddressData,
  GetAddressDataAddressDataGetAddressDataGet200,
  GetAddressDataAddressDataGetAddressDataGetParams,
  GetAddressPointNamesAddressDataAutocompleteAddressPointGetParams,
  GetCityNamesAddressDataAutocompleteCityGetParams,
  GetStreetNamesAddressDataAutocompleteStreetGetParams,
  GetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetParams,
  HTTPValidationError
} from '.././model';



  
  
  
/**
 * Returns voivodeship names that match the query
 * @summary Get Voivodeship Names
 */
export type getVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetResponse200 = {
  data: AutocompleteAddressData[]
  status: 200
}

export type getVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetResponseSuccess = (getVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetResponse200) & {
  headers: Headers;
};
export type getVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetResponseError = (getVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetResponse422) & {
  headers: Headers;
};

export type getVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetResponse = (getVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetResponseSuccess | getVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetResponseError)

export const getGetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetUrl = (params?: GetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/address_data/autocomplete/voivodeship?${stringifiedParams}` : `/address_data/autocomplete/voivodeship`
}

export const getVoivodeshipNamesAddressDataAutocompleteVoivodeshipGet = async (params?: GetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetParams, options?: RequestInit): Promise<getVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetResponse> => {
  
  const res = await fetch(getGetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetResponse
}




export const getGetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetKey = (params?: GetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetParams,) => [`/address_data/autocomplete/voivodeship`, ...(params ? [params]: [])] as const;

export type GetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetQueryResult = NonNullable<Awaited<ReturnType<typeof getVoivodeshipNamesAddressDataAutocompleteVoivodeshipGet>>>
export type GetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetQueryError = Promise<HTTPValidationError>

/**
 * @summary Get Voivodeship Names
 */
export const useGetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGet = <TError = Promise<HTTPValidationError>>(
  params?: GetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getVoivodeshipNamesAddressDataAutocompleteVoivodeshipGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetVoivodeshipNamesAddressDataAutocompleteVoivodeshipGetKey(params) : null);
  const swrFn = () => getVoivodeshipNamesAddressDataAutocompleteVoivodeshipGet(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Returns city names that match the query
 * @summary Get City Names
 */
export type getCityNamesAddressDataAutocompleteCityGetResponse200 = {
  data: AutocompleteAddressData[]
  status: 200
}

export type getCityNamesAddressDataAutocompleteCityGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getCityNamesAddressDataAutocompleteCityGetResponseSuccess = (getCityNamesAddressDataAutocompleteCityGetResponse200) & {
  headers: Headers;
};
export type getCityNamesAddressDataAutocompleteCityGetResponseError = (getCityNamesAddressDataAutocompleteCityGetResponse422) & {
  headers: Headers;
};

export type getCityNamesAddressDataAutocompleteCityGetResponse = (getCityNamesAddressDataAutocompleteCityGetResponseSuccess | getCityNamesAddressDataAutocompleteCityGetResponseError)

export const getGetCityNamesAddressDataAutocompleteCityGetUrl = (params: GetCityNamesAddressDataAutocompleteCityGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/address_data/autocomplete/city?${stringifiedParams}` : `/address_data/autocomplete/city`
}

export const getCityNamesAddressDataAutocompleteCityGet = async (params: GetCityNamesAddressDataAutocompleteCityGetParams, options?: RequestInit): Promise<getCityNamesAddressDataAutocompleteCityGetResponse> => {
  
  const res = await fetch(getGetCityNamesAddressDataAutocompleteCityGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getCityNamesAddressDataAutocompleteCityGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCityNamesAddressDataAutocompleteCityGetResponse
}




export const getGetCityNamesAddressDataAutocompleteCityGetKey = (params: GetCityNamesAddressDataAutocompleteCityGetParams,) => [`/address_data/autocomplete/city`, ...(params ? [params]: [])] as const;

export type GetCityNamesAddressDataAutocompleteCityGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCityNamesAddressDataAutocompleteCityGet>>>
export type GetCityNamesAddressDataAutocompleteCityGetQueryError = Promise<HTTPValidationError>

/**
 * @summary Get City Names
 */
export const useGetCityNamesAddressDataAutocompleteCityGet = <TError = Promise<HTTPValidationError>>(
  params: GetCityNamesAddressDataAutocompleteCityGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getCityNamesAddressDataAutocompleteCityGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetCityNamesAddressDataAutocompleteCityGetKey(params) : null);
  const swrFn = () => getCityNamesAddressDataAutocompleteCityGet(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Returns street names that match the query
 * @summary Get Street Names
 */
export type getStreetNamesAddressDataAutocompleteStreetGetResponse200 = {
  data: AutocompleteAddressData[]
  status: 200
}

export type getStreetNamesAddressDataAutocompleteStreetGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getStreetNamesAddressDataAutocompleteStreetGetResponseSuccess = (getStreetNamesAddressDataAutocompleteStreetGetResponse200) & {
  headers: Headers;
};
export type getStreetNamesAddressDataAutocompleteStreetGetResponseError = (getStreetNamesAddressDataAutocompleteStreetGetResponse422) & {
  headers: Headers;
};

export type getStreetNamesAddressDataAutocompleteStreetGetResponse = (getStreetNamesAddressDataAutocompleteStreetGetResponseSuccess | getStreetNamesAddressDataAutocompleteStreetGetResponseError)

export const getGetStreetNamesAddressDataAutocompleteStreetGetUrl = (params: GetStreetNamesAddressDataAutocompleteStreetGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/address_data/autocomplete/street?${stringifiedParams}` : `/address_data/autocomplete/street`
}

export const getStreetNamesAddressDataAutocompleteStreetGet = async (params: GetStreetNamesAddressDataAutocompleteStreetGetParams, options?: RequestInit): Promise<getStreetNamesAddressDataAutocompleteStreetGetResponse> => {
  
  const res = await fetch(getGetStreetNamesAddressDataAutocompleteStreetGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getStreetNamesAddressDataAutocompleteStreetGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getStreetNamesAddressDataAutocompleteStreetGetResponse
}




export const getGetStreetNamesAddressDataAutocompleteStreetGetKey = (params: GetStreetNamesAddressDataAutocompleteStreetGetParams,) => [`/address_data/autocomplete/street`, ...(params ? [params]: [])] as const;

export type GetStreetNamesAddressDataAutocompleteStreetGetQueryResult = NonNullable<Awaited<ReturnType<typeof getStreetNamesAddressDataAutocompleteStreetGet>>>
export type GetStreetNamesAddressDataAutocompleteStreetGetQueryError = Promise<HTTPValidationError>

/**
 * @summary Get Street Names
 */
export const useGetStreetNamesAddressDataAutocompleteStreetGet = <TError = Promise<HTTPValidationError>>(
  params: GetStreetNamesAddressDataAutocompleteStreetGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getStreetNamesAddressDataAutocompleteStreetGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetStreetNamesAddressDataAutocompleteStreetGetKey(params) : null);
  const swrFn = () => getStreetNamesAddressDataAutocompleteStreetGet(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Returns address point house numbers that match the query
 * @summary Get Address Point Names
 */
export type getAddressPointNamesAddressDataAutocompleteAddressPointGetResponse200 = {
  data: AutocompleteAddressData[]
  status: 200
}

export type getAddressPointNamesAddressDataAutocompleteAddressPointGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getAddressPointNamesAddressDataAutocompleteAddressPointGetResponseSuccess = (getAddressPointNamesAddressDataAutocompleteAddressPointGetResponse200) & {
  headers: Headers;
};
export type getAddressPointNamesAddressDataAutocompleteAddressPointGetResponseError = (getAddressPointNamesAddressDataAutocompleteAddressPointGetResponse422) & {
  headers: Headers;
};

export type getAddressPointNamesAddressDataAutocompleteAddressPointGetResponse = (getAddressPointNamesAddressDataAutocompleteAddressPointGetResponseSuccess | getAddressPointNamesAddressDataAutocompleteAddressPointGetResponseError)

export const getGetAddressPointNamesAddressDataAutocompleteAddressPointGetUrl = (params: GetAddressPointNamesAddressDataAutocompleteAddressPointGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/address_data/autocomplete/address_point?${stringifiedParams}` : `/address_data/autocomplete/address_point`
}

export const getAddressPointNamesAddressDataAutocompleteAddressPointGet = async (params: GetAddressPointNamesAddressDataAutocompleteAddressPointGetParams, options?: RequestInit): Promise<getAddressPointNamesAddressDataAutocompleteAddressPointGetResponse> => {
  
  const res = await fetch(getGetAddressPointNamesAddressDataAutocompleteAddressPointGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAddressPointNamesAddressDataAutocompleteAddressPointGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAddressPointNamesAddressDataAutocompleteAddressPointGetResponse
}




export const getGetAddressPointNamesAddressDataAutocompleteAddressPointGetKey = (params: GetAddressPointNamesAddressDataAutocompleteAddressPointGetParams,) => [`/address_data/autocomplete/address_point`, ...(params ? [params]: [])] as const;

export type GetAddressPointNamesAddressDataAutocompleteAddressPointGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAddressPointNamesAddressDataAutocompleteAddressPointGet>>>
export type GetAddressPointNamesAddressDataAutocompleteAddressPointGetQueryError = Promise<HTTPValidationError>

/**
 * @summary Get Address Point Names
 */
export const useGetAddressPointNamesAddressDataAutocompleteAddressPointGet = <TError = Promise<HTTPValidationError>>(
  params: GetAddressPointNamesAddressDataAutocompleteAddressPointGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAddressPointNamesAddressDataAutocompleteAddressPointGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAddressPointNamesAddressDataAutocompleteAddressPointGetKey(params) : null);
  const swrFn = () => getAddressPointNamesAddressDataAutocompleteAddressPointGet(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Returns data about building at given address point
 * @summary Get Address Data
 */
export type getAddressDataAddressDataGetAddressDataGetResponse200 = {
  data: GetAddressDataAddressDataGetAddressDataGet200
  status: 200
}

export type getAddressDataAddressDataGetAddressDataGetResponse404 = {
  data: void
  status: 404
}

export type getAddressDataAddressDataGetAddressDataGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getAddressDataAddressDataGetAddressDataGetResponseSuccess = (getAddressDataAddressDataGetAddressDataGetResponse200) & {
  headers: Headers;
};
export type getAddressDataAddressDataGetAddressDataGetResponseError = (getAddressDataAddressDataGetAddressDataGetResponse404 | getAddressDataAddressDataGetAddressDataGetResponse422) & {
  headers: Headers;
};

export type getAddressDataAddressDataGetAddressDataGetResponse = (getAddressDataAddressDataGetAddressDataGetResponseSuccess | getAddressDataAddressDataGetAddressDataGetResponseError)

export const getGetAddressDataAddressDataGetAddressDataGetUrl = (params: GetAddressDataAddressDataGetAddressDataGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/address_data/get_address_data?${stringifiedParams}` : `/address_data/get_address_data`
}

export const getAddressDataAddressDataGetAddressDataGet = async (params: GetAddressDataAddressDataGetAddressDataGetParams, options?: RequestInit): Promise<getAddressDataAddressDataGetAddressDataGetResponse> => {
  
  const res = await fetch(getGetAddressDataAddressDataGetAddressDataGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAddressDataAddressDataGetAddressDataGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAddressDataAddressDataGetAddressDataGetResponse
}




export const getGetAddressDataAddressDataGetAddressDataGetKey = (params: GetAddressDataAddressDataGetAddressDataGetParams,) => [`/address_data/get_address_data`, ...(params ? [params]: [])] as const;

export type GetAddressDataAddressDataGetAddressDataGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAddressDataAddressDataGetAddressDataGet>>>
export type GetAddressDataAddressDataGetAddressDataGetQueryError = Promise<void | HTTPValidationError>

/**
 * @summary Get Address Data
 */
export const useGetAddressDataAddressDataGetAddressDataGet = <TError = Promise<void | HTTPValidationError>>(
  params: GetAddressDataAddressDataGetAddressDataGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAddressDataAddressDataGetAddressDataGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAddressDataAddressDataGetAddressDataGetKey(params) : null);
  const swrFn = () => getAddressDataAddressDataGetAddressDataGet(params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
