/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  BodyAddWorkspaceWorkspacePatch,
  BodyCreateWorkspaceWorkspacePost,
  BodySetWorkspaceWorkspaceSetPatch,
  BodyUpdateWorkspaceWorkspacePut,
  HTTPValidationError,
  StateResponse
} from '.././model';



  
  
  
/**
 * Returns all workspaces for the user
 * @summary Get All Workspaces
 */
export type getAllWorkspacesWorkspaceAllGetResponse200 = {
  data: [string, string][]
  status: 200
}
    
export type getAllWorkspacesWorkspaceAllGetResponseSuccess = (getAllWorkspacesWorkspaceAllGetResponse200) & {
  headers: Headers;
};
;

export type getAllWorkspacesWorkspaceAllGetResponse = (getAllWorkspacesWorkspaceAllGetResponseSuccess)

export const getGetAllWorkspacesWorkspaceAllGetUrl = () => {


  

  return `/workspace/all`
}

export const getAllWorkspacesWorkspaceAllGet = async ( options?: RequestInit): Promise<getAllWorkspacesWorkspaceAllGetResponse> => {
  
  const res = await fetch(getGetAllWorkspacesWorkspaceAllGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllWorkspacesWorkspaceAllGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllWorkspacesWorkspaceAllGetResponse
}




export const getGetAllWorkspacesWorkspaceAllGetKey = () => [`/workspace/all`] as const;

export type GetAllWorkspacesWorkspaceAllGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAllWorkspacesWorkspaceAllGet>>>
export type GetAllWorkspacesWorkspaceAllGetQueryError = Promise<unknown>

/**
 * @summary Get All Workspaces
 */
export const useGetAllWorkspacesWorkspaceAllGet = <TError = Promise<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAllWorkspacesWorkspaceAllGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAllWorkspacesWorkspaceAllGetKey() : null);
  const swrFn = () => getAllWorkspacesWorkspaceAllGet(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Returns the current workspace for the user
 * @summary Get Current Workspace
 */
export type getCurrentWorkspaceWorkspaceCurrentGetResponse200 = {
  data: [string, string]
  status: 200
}
    
export type getCurrentWorkspaceWorkspaceCurrentGetResponseSuccess = (getCurrentWorkspaceWorkspaceCurrentGetResponse200) & {
  headers: Headers;
};
;

export type getCurrentWorkspaceWorkspaceCurrentGetResponse = (getCurrentWorkspaceWorkspaceCurrentGetResponseSuccess)

export const getGetCurrentWorkspaceWorkspaceCurrentGetUrl = () => {


  

  return `/workspace/current`
}

export const getCurrentWorkspaceWorkspaceCurrentGet = async ( options?: RequestInit): Promise<getCurrentWorkspaceWorkspaceCurrentGetResponse> => {
  
  const res = await fetch(getGetCurrentWorkspaceWorkspaceCurrentGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getCurrentWorkspaceWorkspaceCurrentGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCurrentWorkspaceWorkspaceCurrentGetResponse
}




export const getGetCurrentWorkspaceWorkspaceCurrentGetKey = () => [`/workspace/current`] as const;

export type GetCurrentWorkspaceWorkspaceCurrentGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentWorkspaceWorkspaceCurrentGet>>>
export type GetCurrentWorkspaceWorkspaceCurrentGetQueryError = Promise<unknown>

/**
 * @summary Get Current Workspace
 */
export const useGetCurrentWorkspaceWorkspaceCurrentGet = <TError = Promise<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getCurrentWorkspaceWorkspaceCurrentGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetCurrentWorkspaceWorkspaceCurrentGetKey() : null);
  const swrFn = () => getCurrentWorkspaceWorkspaceCurrentGet(fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Updates the name of a workspace for the user
 * @summary Update Workspace
 */
export type updateWorkspaceWorkspacePutResponse200 = {
  data: StateResponse
  status: 200
}

export type updateWorkspaceWorkspacePutResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type updateWorkspaceWorkspacePutResponseSuccess = (updateWorkspaceWorkspacePutResponse200) & {
  headers: Headers;
};
export type updateWorkspaceWorkspacePutResponseError = (updateWorkspaceWorkspacePutResponse422) & {
  headers: Headers;
};

export type updateWorkspaceWorkspacePutResponse = (updateWorkspaceWorkspacePutResponseSuccess | updateWorkspaceWorkspacePutResponseError)

export const getUpdateWorkspaceWorkspacePutUrl = () => {


  

  return `/workspace/`
}

export const updateWorkspaceWorkspacePut = async (bodyUpdateWorkspaceWorkspacePut: BodyUpdateWorkspaceWorkspacePut, options?: RequestInit): Promise<updateWorkspaceWorkspacePutResponse> => {
  
  const res = await fetch(getUpdateWorkspaceWorkspacePutUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bodyUpdateWorkspaceWorkspacePut,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateWorkspaceWorkspacePutResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateWorkspaceWorkspacePutResponse
}




export const getUpdateWorkspaceWorkspacePutMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: BodyUpdateWorkspaceWorkspacePut }) => {
    return updateWorkspaceWorkspacePut(arg, options);
  }
}
export const getUpdateWorkspaceWorkspacePutMutationKey = () => [`/workspace/`] as const;

export type UpdateWorkspaceWorkspacePutMutationResult = NonNullable<Awaited<ReturnType<typeof updateWorkspaceWorkspacePut>>>
export type UpdateWorkspaceWorkspacePutMutationError = Promise<HTTPValidationError>

/**
 * @summary Update Workspace
 */
export const useUpdateWorkspaceWorkspacePut = <TError = Promise<HTTPValidationError>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateWorkspaceWorkspacePut>>, TError, Key, BodyUpdateWorkspaceWorkspacePut, Awaited<ReturnType<typeof updateWorkspaceWorkspacePut>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateWorkspaceWorkspacePutMutationKey();
  const swrFn = getUpdateWorkspaceWorkspacePutMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Creates a new workspace for the user
 * @summary Create Workspace
 */
export type createWorkspaceWorkspacePostResponse201 = {
  data: string
  status: 201
}

export type createWorkspaceWorkspacePostResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type createWorkspaceWorkspacePostResponseSuccess = (createWorkspaceWorkspacePostResponse201) & {
  headers: Headers;
};
export type createWorkspaceWorkspacePostResponseError = (createWorkspaceWorkspacePostResponse422) & {
  headers: Headers;
};

export type createWorkspaceWorkspacePostResponse = (createWorkspaceWorkspacePostResponseSuccess | createWorkspaceWorkspacePostResponseError)

export const getCreateWorkspaceWorkspacePostUrl = () => {


  

  return `/workspace/`
}

export const createWorkspaceWorkspacePost = async (bodyCreateWorkspaceWorkspacePost: BodyCreateWorkspaceWorkspacePost, options?: RequestInit): Promise<createWorkspaceWorkspacePostResponse> => {
  
  const res = await fetch(getCreateWorkspaceWorkspacePostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bodyCreateWorkspaceWorkspacePost,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createWorkspaceWorkspacePostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createWorkspaceWorkspacePostResponse
}




export const getCreateWorkspaceWorkspacePostMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: BodyCreateWorkspaceWorkspacePost }) => {
    return createWorkspaceWorkspacePost(arg, options);
  }
}
export const getCreateWorkspaceWorkspacePostMutationKey = () => [`/workspace/`] as const;

export type CreateWorkspaceWorkspacePostMutationResult = NonNullable<Awaited<ReturnType<typeof createWorkspaceWorkspacePost>>>
export type CreateWorkspaceWorkspacePostMutationError = Promise<HTTPValidationError>

/**
 * @summary Create Workspace
 */
export const useCreateWorkspaceWorkspacePost = <TError = Promise<HTTPValidationError>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createWorkspaceWorkspacePost>>, TError, Key, BodyCreateWorkspaceWorkspacePost, Awaited<ReturnType<typeof createWorkspaceWorkspacePost>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateWorkspaceWorkspacePostMutationKey();
  const swrFn = getCreateWorkspaceWorkspacePostMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Adds an existing workspace to the user
 * @summary Add Workspace
 */
export type addWorkspaceWorkspacePatchResponse200 = {
  data: StateResponse
  status: 200
}

export type addWorkspaceWorkspacePatchResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type addWorkspaceWorkspacePatchResponseSuccess = (addWorkspaceWorkspacePatchResponse200) & {
  headers: Headers;
};
export type addWorkspaceWorkspacePatchResponseError = (addWorkspaceWorkspacePatchResponse422) & {
  headers: Headers;
};

export type addWorkspaceWorkspacePatchResponse = (addWorkspaceWorkspacePatchResponseSuccess | addWorkspaceWorkspacePatchResponseError)

export const getAddWorkspaceWorkspacePatchUrl = () => {


  

  return `/workspace/`
}

export const addWorkspaceWorkspacePatch = async (bodyAddWorkspaceWorkspacePatch: BodyAddWorkspaceWorkspacePatch, options?: RequestInit): Promise<addWorkspaceWorkspacePatchResponse> => {
  
  const res = await fetch(getAddWorkspaceWorkspacePatchUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bodyAddWorkspaceWorkspacePatch,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: addWorkspaceWorkspacePatchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as addWorkspaceWorkspacePatchResponse
}




export const getAddWorkspaceWorkspacePatchMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: BodyAddWorkspaceWorkspacePatch }) => {
    return addWorkspaceWorkspacePatch(arg, options);
  }
}
export const getAddWorkspaceWorkspacePatchMutationKey = () => [`/workspace/`] as const;

export type AddWorkspaceWorkspacePatchMutationResult = NonNullable<Awaited<ReturnType<typeof addWorkspaceWorkspacePatch>>>
export type AddWorkspaceWorkspacePatchMutationError = Promise<HTTPValidationError>

/**
 * @summary Add Workspace
 */
export const useAddWorkspaceWorkspacePatch = <TError = Promise<HTTPValidationError>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof addWorkspaceWorkspacePatch>>, TError, Key, BodyAddWorkspaceWorkspacePatch, Awaited<ReturnType<typeof addWorkspaceWorkspacePatch>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getAddWorkspaceWorkspacePatchMutationKey();
  const swrFn = getAddWorkspaceWorkspacePatchMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Deletes a workspace for the user
 * @summary Delete Workspace
 */
export type deleteWorkspaceWorkspaceWorkspaceIdDeleteResponse200 = {
  data: StateResponse
  status: 200
}

export type deleteWorkspaceWorkspaceWorkspaceIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type deleteWorkspaceWorkspaceWorkspaceIdDeleteResponseSuccess = (deleteWorkspaceWorkspaceWorkspaceIdDeleteResponse200) & {
  headers: Headers;
};
export type deleteWorkspaceWorkspaceWorkspaceIdDeleteResponseError = (deleteWorkspaceWorkspaceWorkspaceIdDeleteResponse422) & {
  headers: Headers;
};

export type deleteWorkspaceWorkspaceWorkspaceIdDeleteResponse = (deleteWorkspaceWorkspaceWorkspaceIdDeleteResponseSuccess | deleteWorkspaceWorkspaceWorkspaceIdDeleteResponseError)

export const getDeleteWorkspaceWorkspaceWorkspaceIdDeleteUrl = (workspaceId: string,) => {


  

  return `/workspace/${workspaceId}`
}

export const deleteWorkspaceWorkspaceWorkspaceIdDelete = async (workspaceId: string, options?: RequestInit): Promise<deleteWorkspaceWorkspaceWorkspaceIdDeleteResponse> => {
  
  const res = await fetch(getDeleteWorkspaceWorkspaceWorkspaceIdDeleteUrl(workspaceId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteWorkspaceWorkspaceWorkspaceIdDeleteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteWorkspaceWorkspaceWorkspaceIdDeleteResponse
}




export const getDeleteWorkspaceWorkspaceWorkspaceIdDeleteMutationFetcher = (workspaceId: string, options?: RequestInit) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteWorkspaceWorkspaceWorkspaceIdDelete(workspaceId, options);
  }
}
export const getDeleteWorkspaceWorkspaceWorkspaceIdDeleteMutationKey = (workspaceId: string,) => [`/workspace/${workspaceId}`] as const;

export type DeleteWorkspaceWorkspaceWorkspaceIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWorkspaceWorkspaceWorkspaceIdDelete>>>
export type DeleteWorkspaceWorkspaceWorkspaceIdDeleteMutationError = Promise<HTTPValidationError>

/**
 * @summary Delete Workspace
 */
export const useDeleteWorkspaceWorkspaceWorkspaceIdDelete = <TError = Promise<HTTPValidationError>>(
  workspaceId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteWorkspaceWorkspaceWorkspaceIdDelete>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteWorkspaceWorkspaceWorkspaceIdDelete>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteWorkspaceWorkspaceWorkspaceIdDeleteMutationKey(workspaceId);
  const swrFn = getDeleteWorkspaceWorkspaceWorkspaceIdDeleteMutationFetcher(workspaceId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Sets the current workspace for the user
 * @summary Set Workspace
 */
export type setWorkspaceWorkspaceSetPatchResponse200 = {
  data: StateResponse
  status: 200
}

export type setWorkspaceWorkspaceSetPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type setWorkspaceWorkspaceSetPatchResponseSuccess = (setWorkspaceWorkspaceSetPatchResponse200) & {
  headers: Headers;
};
export type setWorkspaceWorkspaceSetPatchResponseError = (setWorkspaceWorkspaceSetPatchResponse422) & {
  headers: Headers;
};

export type setWorkspaceWorkspaceSetPatchResponse = (setWorkspaceWorkspaceSetPatchResponseSuccess | setWorkspaceWorkspaceSetPatchResponseError)

export const getSetWorkspaceWorkspaceSetPatchUrl = () => {


  

  return `/workspace/set`
}

export const setWorkspaceWorkspaceSetPatch = async (bodySetWorkspaceWorkspaceSetPatch: BodySetWorkspaceWorkspaceSetPatch, options?: RequestInit): Promise<setWorkspaceWorkspaceSetPatchResponse> => {
  
  const res = await fetch(getSetWorkspaceWorkspaceSetPatchUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bodySetWorkspaceWorkspaceSetPatch,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: setWorkspaceWorkspaceSetPatchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as setWorkspaceWorkspaceSetPatchResponse
}




export const getSetWorkspaceWorkspaceSetPatchMutationFetcher = ( options?: RequestInit) => {
  return (_: Key, { arg }: { arg: BodySetWorkspaceWorkspaceSetPatch }) => {
    return setWorkspaceWorkspaceSetPatch(arg, options);
  }
}
export const getSetWorkspaceWorkspaceSetPatchMutationKey = () => [`/workspace/set`] as const;

export type SetWorkspaceWorkspaceSetPatchMutationResult = NonNullable<Awaited<ReturnType<typeof setWorkspaceWorkspaceSetPatch>>>
export type SetWorkspaceWorkspaceSetPatchMutationError = Promise<HTTPValidationError>

/**
 * @summary Set Workspace
 */
export const useSetWorkspaceWorkspaceSetPatch = <TError = Promise<HTTPValidationError>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof setWorkspaceWorkspaceSetPatch>>, TError, Key, BodySetWorkspaceWorkspaceSetPatch, Awaited<ReturnType<typeof setWorkspaceWorkspaceSetPatch>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getSetWorkspaceWorkspaceSetPatchMutationKey();
  const swrFn = getSetWorkspaceWorkspaceSetPatchMutationFetcher(fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
