/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Arguments,
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  BodyAddWorkspaceWorkspacePatch,
  BodyCreateWorkspaceWorkspacePost,
  BodySetWorkspaceWorkspaceSetPatch,
  BodyUpdateWorkspaceWorkspacePut,
  HTTPValidationError,
  StateResponse
} from '.././model';



  
  
  
/**
 * Returns all workspaces for the user
 * @summary Get All Workspaces
 */
export const getAllWorkspacesWorkspaceAllGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<[string, string][]>> => {
    return axios.get(
      `/workspace/all`,options
    );
  }



export const getGetAllWorkspacesWorkspaceAllGetKey = () => [`/workspace/all`] as const;

export type GetAllWorkspacesWorkspaceAllGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAllWorkspacesWorkspaceAllGet>>>
export type GetAllWorkspacesWorkspaceAllGetQueryError = AxiosError<unknown>

/**
 * @summary Get All Workspaces
 */
export const useGetAllWorkspacesWorkspaceAllGet = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getAllWorkspacesWorkspaceAllGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetAllWorkspacesWorkspaceAllGetKey() : null);
  const swrFn = () => getAllWorkspacesWorkspaceAllGet(axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Returns the current workspace for the user
 * @summary Get Current Workspace
 */
export const getCurrentWorkspaceWorkspaceCurrentGet = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<[string, string]>> => {
    return axios.get(
      `/workspace/current`,options
    );
  }



export const getGetCurrentWorkspaceWorkspaceCurrentGetKey = () => [`/workspace/current`] as const;

export type GetCurrentWorkspaceWorkspaceCurrentGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentWorkspaceWorkspaceCurrentGet>>>
export type GetCurrentWorkspaceWorkspaceCurrentGetQueryError = AxiosError<unknown>

/**
 * @summary Get Current Workspace
 */
export const useGetCurrentWorkspaceWorkspaceCurrentGet = <TError = AxiosError<unknown>>(
   options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getCurrentWorkspaceWorkspaceCurrentGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetCurrentWorkspaceWorkspaceCurrentGetKey() : null);
  const swrFn = () => getCurrentWorkspaceWorkspaceCurrentGet(axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Updates the name of a workspace for the user
 * @summary Update Workspace
 */
export const updateWorkspaceWorkspacePut = (
    bodyUpdateWorkspaceWorkspacePut: BodyUpdateWorkspaceWorkspacePut, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StateResponse>> => {
    return axios.put(
      `/workspace/`,
      bodyUpdateWorkspaceWorkspacePut,options
    );
  }



export const getUpdateWorkspaceWorkspacePutMutationFetcher = ( options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: BodyUpdateWorkspaceWorkspacePut }) => {
    return updateWorkspaceWorkspacePut(arg, options);
  }
}
export const getUpdateWorkspaceWorkspacePutMutationKey = () => [`/workspace/`] as const;

export type UpdateWorkspaceWorkspacePutMutationResult = NonNullable<Awaited<ReturnType<typeof updateWorkspaceWorkspacePut>>>
export type UpdateWorkspaceWorkspacePutMutationError = AxiosError<HTTPValidationError>

/**
 * @summary Update Workspace
 */
export const useUpdateWorkspaceWorkspacePut = <TError = AxiosError<HTTPValidationError>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateWorkspaceWorkspacePut>>, TError, Key, BodyUpdateWorkspaceWorkspacePut, Awaited<ReturnType<typeof updateWorkspaceWorkspacePut>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateWorkspaceWorkspacePutMutationKey();
  const swrFn = getUpdateWorkspaceWorkspacePutMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Creates a new workspace for the user
 * @summary Create Workspace
 */
export const createWorkspaceWorkspacePost = (
    bodyCreateWorkspaceWorkspacePost: BodyCreateWorkspaceWorkspacePost, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    return axios.post(
      `/workspace/`,
      bodyCreateWorkspaceWorkspacePost,{
        responseType: 'text',
    ...options,}
    );
  }



export const getCreateWorkspaceWorkspacePostMutationFetcher = ( options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: BodyCreateWorkspaceWorkspacePost }) => {
    return createWorkspaceWorkspacePost(arg, options);
  }
}
export const getCreateWorkspaceWorkspacePostMutationKey = () => [`/workspace/`] as const;

export type CreateWorkspaceWorkspacePostMutationResult = NonNullable<Awaited<ReturnType<typeof createWorkspaceWorkspacePost>>>
export type CreateWorkspaceWorkspacePostMutationError = AxiosError<HTTPValidationError>

/**
 * @summary Create Workspace
 */
export const useCreateWorkspaceWorkspacePost = <TError = AxiosError<HTTPValidationError>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof createWorkspaceWorkspacePost>>, TError, Key, BodyCreateWorkspaceWorkspacePost, Awaited<ReturnType<typeof createWorkspaceWorkspacePost>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getCreateWorkspaceWorkspacePostMutationKey();
  const swrFn = getCreateWorkspaceWorkspacePostMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Adds an existing workspace to the user
 * @summary Add Workspace
 */
export const addWorkspaceWorkspacePatch = (
    bodyAddWorkspaceWorkspacePatch: BodyAddWorkspaceWorkspacePatch, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StateResponse>> => {
    return axios.patch(
      `/workspace/`,
      bodyAddWorkspaceWorkspacePatch,options
    );
  }



export const getAddWorkspaceWorkspacePatchMutationFetcher = ( options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: BodyAddWorkspaceWorkspacePatch }) => {
    return addWorkspaceWorkspacePatch(arg, options);
  }
}
export const getAddWorkspaceWorkspacePatchMutationKey = () => [`/workspace/`] as const;

export type AddWorkspaceWorkspacePatchMutationResult = NonNullable<Awaited<ReturnType<typeof addWorkspaceWorkspacePatch>>>
export type AddWorkspaceWorkspacePatchMutationError = AxiosError<HTTPValidationError>

/**
 * @summary Add Workspace
 */
export const useAddWorkspaceWorkspacePatch = <TError = AxiosError<HTTPValidationError>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof addWorkspaceWorkspacePatch>>, TError, Key, BodyAddWorkspaceWorkspacePatch, Awaited<ReturnType<typeof addWorkspaceWorkspacePatch>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getAddWorkspaceWorkspacePatchMutationKey();
  const swrFn = getAddWorkspaceWorkspacePatchMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Deletes a workspace for the user
 * @summary Delete Workspace
 */
export const deleteWorkspaceWorkspaceWorkspaceIdDelete = (
    workspaceId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StateResponse>> => {
    return axios.delete(
      `/workspace/${workspaceId}`,options
    );
  }



export const getDeleteWorkspaceWorkspaceWorkspaceIdDeleteMutationFetcher = (workspaceId: string, options?: AxiosRequestConfig) => {
  return (_: Key, __: { arg: Arguments }) => {
    return deleteWorkspaceWorkspaceWorkspaceIdDelete(workspaceId, options);
  }
}
export const getDeleteWorkspaceWorkspaceWorkspaceIdDeleteMutationKey = (workspaceId: string,) => [`/workspace/${workspaceId}`] as const;

export type DeleteWorkspaceWorkspaceWorkspaceIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWorkspaceWorkspaceWorkspaceIdDelete>>>
export type DeleteWorkspaceWorkspaceWorkspaceIdDeleteMutationError = AxiosError<HTTPValidationError>

/**
 * @summary Delete Workspace
 */
export const useDeleteWorkspaceWorkspaceWorkspaceIdDelete = <TError = AxiosError<HTTPValidationError>>(
  workspaceId: string, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof deleteWorkspaceWorkspaceWorkspaceIdDelete>>, TError, Key, Arguments, Awaited<ReturnType<typeof deleteWorkspaceWorkspaceWorkspaceIdDelete>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getDeleteWorkspaceWorkspaceWorkspaceIdDeleteMutationKey(workspaceId);
  const swrFn = getDeleteWorkspaceWorkspaceWorkspaceIdDeleteMutationFetcher(workspaceId, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Sets the current workspace for the user
 * @summary Set Workspace
 */
export const setWorkspaceWorkspaceSetPatch = (
    bodySetWorkspaceWorkspaceSetPatch: BodySetWorkspaceWorkspaceSetPatch, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<StateResponse>> => {
    return axios.patch(
      `/workspace/set`,
      bodySetWorkspaceWorkspaceSetPatch,options
    );
  }



export const getSetWorkspaceWorkspaceSetPatchMutationFetcher = ( options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: BodySetWorkspaceWorkspaceSetPatch }) => {
    return setWorkspaceWorkspaceSetPatch(arg, options);
  }
}
export const getSetWorkspaceWorkspaceSetPatchMutationKey = () => [`/workspace/set`] as const;

export type SetWorkspaceWorkspaceSetPatchMutationResult = NonNullable<Awaited<ReturnType<typeof setWorkspaceWorkspaceSetPatch>>>
export type SetWorkspaceWorkspaceSetPatchMutationError = AxiosError<HTTPValidationError>

/**
 * @summary Set Workspace
 */
export const useSetWorkspaceWorkspaceSetPatch = <TError = AxiosError<HTTPValidationError>>(
   options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof setWorkspaceWorkspaceSetPatch>>, TError, Key, BodySetWorkspaceWorkspaceSetPatch, Awaited<ReturnType<typeof setWorkspaceWorkspaceSetPatch>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getSetWorkspaceWorkspaceSetPatchMutationKey();
  const swrFn = getSetWorkspaceWorkspaceSetPatchMutationFetcher(axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
