/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  StateResponse
} from '.././model';


export const getGetAllWorkspacesWorkspaceAllGetResponseMock = (): [string, string][] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ([])))

export const getGetCurrentWorkspaceWorkspaceCurrentGetResponseMock = (): [string, string] => ([])

export const getUpdateWorkspaceWorkspacePutResponseMock = (): StateResponse => (faker.helpers.arrayElement(['SUCCESS','ERROR'] as const))

export const getCreateWorkspaceWorkspacePostResponseMock = (): string => (faker.word.sample())

export const getAddWorkspaceWorkspacePatchResponseMock = (): StateResponse => (faker.helpers.arrayElement(['SUCCESS','ERROR'] as const))

export const getDeleteWorkspaceWorkspaceWorkspaceIdDeleteResponseMock = (): StateResponse => (faker.helpers.arrayElement(['SUCCESS','ERROR'] as const))

export const getSetWorkspaceWorkspaceSetPatchResponseMock = (): StateResponse => (faker.helpers.arrayElement(['SUCCESS','ERROR'] as const))


export const getGetAllWorkspacesWorkspaceAllGetMockHandler = (overrideResponse?: [string, string][] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<[string, string][]> | [string, string][]), options?: RequestHandlerOptions) => {
  return http.get('*/workspace/all', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetAllWorkspacesWorkspaceAllGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetCurrentWorkspaceWorkspaceCurrentGetMockHandler = (overrideResponse?: [string, string] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<[string, string]> | [string, string]), options?: RequestHandlerOptions) => {
  return http.get('*/workspace/current', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetCurrentWorkspaceWorkspaceCurrentGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateWorkspaceWorkspacePutMockHandler = (overrideResponse?: StateResponse | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<StateResponse> | StateResponse), options?: RequestHandlerOptions) => {
  return http.put('*/workspace/', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateWorkspaceWorkspacePutResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getCreateWorkspaceWorkspacePostMockHandler = (overrideResponse?: string | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<string> | string), options?: RequestHandlerOptions) => {
  return http.post('*/workspace/', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateWorkspaceWorkspacePostResponseMock()),
      { status: 201,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getAddWorkspaceWorkspacePatchMockHandler = (overrideResponse?: StateResponse | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<StateResponse> | StateResponse), options?: RequestHandlerOptions) => {
  return http.patch('*/workspace/', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getAddWorkspaceWorkspacePatchResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getDeleteWorkspaceWorkspaceWorkspaceIdDeleteMockHandler = (overrideResponse?: StateResponse | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<StateResponse> | StateResponse), options?: RequestHandlerOptions) => {
  return http.delete('*/workspace/:workspaceId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeleteWorkspaceWorkspaceWorkspaceIdDeleteResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getSetWorkspaceWorkspaceSetPatchMockHandler = (overrideResponse?: StateResponse | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<StateResponse> | StateResponse), options?: RequestHandlerOptions) => {
  return http.patch('*/workspace/set', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getSetWorkspaceWorkspaceSetPatchResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getWorkspaceMock = () => [
  getGetAllWorkspacesWorkspaceAllGetMockHandler(),
  getGetCurrentWorkspaceWorkspaceCurrentGetMockHandler(),
  getUpdateWorkspaceWorkspacePutMockHandler(),
  getCreateWorkspaceWorkspacePostMockHandler(),
  getAddWorkspaceWorkspacePatchMockHandler(),
  getDeleteWorkspaceWorkspaceWorkspaceIdDeleteMockHandler(),
  getSetWorkspaceWorkspaceSetPatchMockHandler()
]
