/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface BodyUpdateOptimizationNameOptimizationOptIdNamePut {
  /**
   * New name for the optimization
   * @minLength 1
   * @maxLength 50
   */
  new_name: string;
}
