/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface BodyAddWorkspaceWorkspacePatch {
  /** ID of the workspace to add */
  workspace_id: string;
  /** Name of the workspace to add */
  workspace_name: string;
}
