/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface BodyCloneOptimizationOptimizationOptIdClonePost {
  /**
   * Name for the cloned optimization
   * @minLength 1
   * @maxLength 50
   */
  name?: string;
  remove_existing?: boolean;
}
