/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface BodyCreateWorkspaceWorkspacePost {
  /** Name of the new workspace */
  workspace_name: string;
}
