/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface BodyUpdateWorkspaceWorkspacePut {
  /** ID of the workspace to update */
  workspace_id: string;
  /** New name for the workspace */
  workspace_name: string;
}
