/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type BuildingType = typeof BuildingType[keyof typeof BuildingType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BuildingType = {
  Detached: 'Detached',
  'Semi-detached': 'Semi-detached',
  Terraced: 'Terraced',
} as const;
