/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type Fuel = typeof Fuel[keyof typeof Fuel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Fuel = {
  coal: 'coal',
  wood: 'wood',
  gas: 'gas',
  oil: 'oil',
  virtual_heat_fuel: 'virtual_heat_fuel',
} as const;
