/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type GetAddressPointNamesAddressDataAutocompleteAddressPointGetParams = {
/**
 * @minimum 0
 */
city_id: number;
/**
 * @minimum 0
 */
street_id: number;
/**
 * @minLength 0
 * @maxLength 50
 */
query?: string;
};
