/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type GetStreetNamesAddressDataAutocompleteStreetGetParams = {
/**
 * @minimum 0
 */
city_id: number;
/**
 * @minLength 2
 * @maxLength 50
 */
query?: string;
};
