/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type GetTechnologiesInfoTechnologiesGet200 = {[key: string]: { [key: string]: unknown }};
