/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { LocationDataVoivodeship } from './locationDataVoivodeship';
import type { LocationDataVoivodeshipId } from './locationDataVoivodeshipId';
import type { LocationDataCity } from './locationDataCity';
import type { LocationDataCityId } from './locationDataCityId';
import type { LocationDataStreet } from './locationDataStreet';
import type { LocationDataStreetId } from './locationDataStreetId';
import type { LocationDataHouseNumber } from './locationDataHouseNumber';

export interface LocationData {
  voivodeship: LocationDataVoivodeship;
  voivodeship_id: LocationDataVoivodeshipId;
  city: LocationDataCity;
  city_id: LocationDataCityId;
  street: LocationDataStreet;
  street_id: LocationDataStreetId;
  house_number: LocationDataHouseNumber;
}
