/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { BuildingType } from './buildingType';
import type { Operator } from './operator';
import type { Tariff } from './tariff';

export interface ObjectData {
  building_type: BuildingType;
  build_year: number;
  usable_area: number;
  number_of_floors: number;
  number_of_residents: number;
  total_external_wall_area: number;
  total_window_area: number;
  total_roof_window_area: number;
  total_external_door_area: number;
  total_roof_area: number;
  foundation_area: number;
  volume: number;
  air_exchange_rate: number;
  roof_angle: number;
  operator: Operator;
  tariff: Tariff;
}
