/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type Operator = typeof Operator[keyof typeof Operator];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Operator = {
  Tauron: 'Tauron',
  PGE: 'PGE',
  Energa: 'Energa',
  Enea: 'Enea',
  Other: 'Other',
} as const;
