/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface OptConfig {
  ee_profile: number[];
  pv_profile: number[];
  temp_profile: number[];
  base_heat_profile: number[];
  opt_heat_profile: number[];
  base_total_thermal_transmittance: number;
  base_total_foundation_transmittance: number;
  opt_total_thermal_transmittance: number;
  ventilation_heat_profile: number[];
  /**
   * @minItems 2
   * @maxItems 2
   */
  day_hours: [number, number];
  day_temp: number;
  night_temp: number;
}
