/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { OptimizationResultsCostsModelFUELCOSTS } from './optimizationResultsCostsModelFUELCOSTS';
import type { OptimizationResultsCostsModelVARCOSTS } from './optimizationResultsCostsModelVARCOSTS';

export interface OptimizationResultsCostsModel {
  KSE_COST: unknown;
  OPEX_TOTAL: unknown;
  FUEL_COSTS: OptimizationResultsCostsModelFUELCOSTS;
  VAR_COSTS: OptimizationResultsCostsModelVARCOSTS;
  CAPEX_TOTAL: unknown;
  YEARLY_SAVINGS: unknown;
  PAYBACK_PERIOD: unknown;
}
