/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { LocationData } from './locationData';

export type OptimizationResponseLocationData = LocationData | null;
