/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { OptimizationResponseQueuePosition } from './optimizationResponseQueuePosition';
import type { OptimizationResponseAddressPointId } from './optimizationResponseAddressPointId';
import type { OptimizationResponseLocationData } from './optimizationResponseLocationData';

export interface OptimizationResponse {
  id: number;
  status: string;
  queue_position: OptimizationResponseQueuePosition;
  update_time: string;
  address_point_id: OptimizationResponseAddressPointId;
  location_data: OptimizationResponseLocationData;
  name: string;
}
