/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { OptimizationResultsAnalysisModelPROFIT } from './optimizationResultsAnalysisModelPROFIT';
import type { OptimizationResultsAnalysisModelINSTALLEDCAPACITY } from './optimizationResultsAnalysisModelINSTALLEDCAPACITY';
import type { OptimizationResultsAnalysisModelCAPEX } from './optimizationResultsAnalysisModelCAPEX';
import type { OptimizationResultsAnalysisModelOPEX } from './optimizationResultsAnalysisModelOPEX';

export interface OptimizationResultsAnalysisModel {
  PROFIT: OptimizationResultsAnalysisModelPROFIT;
  INSTALLED_CAPACITY: OptimizationResultsAnalysisModelINSTALLEDCAPACITY;
  CAPEX: OptimizationResultsAnalysisModelCAPEX;
  OPEX: OptimizationResultsAnalysisModelOPEX;
}
