/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { OptimizationResultsSummaryModelENERGYFROMKSE } from './optimizationResultsSummaryModelENERGYFROMKSE';
import type { OptimizationResultsSummaryModelTOTALHEATDEMAND } from './optimizationResultsSummaryModelTOTALHEATDEMAND';
import type { OptimizationResultsSummaryModelTOTALHEATLOSSES } from './optimizationResultsSummaryModelTOTALHEATLOSSES';
import type { OptimizationResultsSummaryModelTOTALVENTILATIONLOSSES } from './optimizationResultsSummaryModelTOTALVENTILATIONLOSSES';
import type { OptimizationResultsSummaryModelNETBILLINGDATA } from './optimizationResultsSummaryModelNETBILLINGDATA';

export interface OptimizationResultsSummaryModel {
  ENERGY_FROM_KSE: OptimizationResultsSummaryModelENERGYFROMKSE;
  TOTAL_HEAT_DEMAND: OptimizationResultsSummaryModelTOTALHEATDEMAND;
  TOTAL_HEAT_LOSSES: OptimizationResultsSummaryModelTOTALHEATLOSSES;
  TOTAL_VENTILATION_LOSSES: OptimizationResultsSummaryModelTOTALVENTILATIONLOSSES;
  NET_BILLING_DATA?: OptimizationResultsSummaryModelNETBILLINGDATA;
}
