/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { OptimizationParamsResponseOperator } from './optimizationParamsResponseOperator';
import type { OptimizationParamsResponseTariff } from './optimizationParamsResponseTariff';

export interface OptimizationParamsResponse {
  operator: OptimizationParamsResponseOperator;
  tariff: OptimizationParamsResponseTariff;
  yearly_ee_demand: number;
  yearly_heat_demand: number;
  yearly_vent_heat_demand: number;
  yearly_opt_vent_heat_demand: number;
  yearly_opt_heat_demand: number;
  pv_potential: number;
  optimal_pv_azimuth: number;
  optimal_pv_slope: number;
}
