/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ProfileDataResponse {
  ee_profile: unknown[];
  pv_profile: unknown[];
  temp_profile: unknown[];
  heat_profile: unknown[];
}
