/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type StateResponse = typeof StateResponse[keyof typeof StateResponse];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StateResponse = {
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
} as const;
