/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type Tariff = typeof Tariff[keyof typeof Tariff];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Tariff = {
  G11: 'G11',
  G12: 'G12',
} as const;
