/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TechnologyParamsFuelName } from './technologyParamsFuelName';
import type { TechnologyParamsFuelCost } from './technologyParamsFuelCost';

export interface TechnologyParams {
  base_capacity: number;
  min_capacity: number;
  max_capacity: number;
  optimize: boolean;
  capex: number;
  opex: number;
  fuel_name?: TechnologyParamsFuelName;
  fuel_cost?: TechnologyParamsFuelCost;
}
