/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type TechnologyType = typeof TechnologyType[keyof typeof TechnologyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TechnologyType = {
  KSE: 'KSE',
  DH: 'DH',
  PV: 'PV',
  HP_AIR: 'HP_AIR',
  BOILER_GAS: 'BOILER_GAS',
  HP_GROUND: 'HP_GROUND',
  BOILER_WOOD: 'BOILER_WOOD',
  BOILER_OIL: 'BOILER_OIL',
  BOILER_COAL: 'BOILER_COAL',
  THERMAL_MODERNIZATION: 'THERMAL_MODERNIZATION',
  BOILER_ELECTRIC: 'BOILER_ELECTRIC',
  SOLAR_HEATING: 'SOLAR_HEATING',
  EE_STORAGE: 'EE_STORAGE',
  HEAT_STORAGE: 'HEAT_STORAGE',
  VENTILATION_HEAT_RECOVERY: 'VENTILATION_HEAT_RECOVERY',
} as const;
