/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ThermoData {
  /**
   * @minimum 0
   * @maximum 10
   */
  thermal_transmittance_external_walls: number;
  /**
   * @minimum 0
   * @maximum 10
   */
  thermal_transmittance_doors: number;
  /**
   * @minimum 0
   * @maximum 10
   */
  thermal_transmittance_windows: number;
  /**
   * @minimum 0
   * @maximum 10
   */
  thermal_transmittance_roof_windows: number;
  /**
   * @minimum 0
   * @maximum 10
   */
  thermal_transmittance_foundation: number;
  /**
   * @minimum 0
   * @maximum 10
   */
  thermal_transmittance_roof: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  ventilation_heat_recovery_efficiency: number;
}
