/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface TotalGenerationResultsModel {
  ENERGY_SOLD_TO_NETWORK: number;
  ENERGY_BOUGHT_BACK_FROM_NETWORK: number;
  [key: string]: unknown;
 }
