/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { SyncParams } from './syncParams';

export interface UserModel {
  uid: string;
  sync_params: SyncParams;
  ip_address: string;
  last_active: string;
  request_count: number;
}
