/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  GetTechnologiesOptimizationOptIdTechnologiesGet200,
  GetTechnologiesOptimizationOptIdTechnologiesGetParams,
  HTTPValidationError,
  UpdateTechnologiesOptimizationOptIdTechnologiesPatch200,
  UpdateTechnologiesOptimizationOptIdTechnologiesPatchBody
} from '.././model';



  
  
  
/**
 * @summary Get Technologies
 */
export const getTechnologiesOptimizationOptIdTechnologiesGet = (
    optId: number,
    params?: GetTechnologiesOptimizationOptIdTechnologiesGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetTechnologiesOptimizationOptIdTechnologiesGet200>> => {
    return axios.get(
      `/optimization/${optId}/technologies`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getGetTechnologiesOptimizationOptIdTechnologiesGetKey = (optId: number,
    params?: GetTechnologiesOptimizationOptIdTechnologiesGetParams,) => [`/optimization/${optId}/technologies`, ...(params ? [params]: [])] as const;

export type GetTechnologiesOptimizationOptIdTechnologiesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTechnologiesOptimizationOptIdTechnologiesGet>>>
export type GetTechnologiesOptimizationOptIdTechnologiesGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get Technologies
 */
export const useGetTechnologiesOptimizationOptIdTechnologiesGet = <TError = AxiosError<HTTPValidationError>>(
  optId: number,
    params?: GetTechnologiesOptimizationOptIdTechnologiesGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getTechnologiesOptimizationOptIdTechnologiesGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(optId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetTechnologiesOptimizationOptIdTechnologiesGetKey(optId,params) : null);
  const swrFn = () => getTechnologiesOptimizationOptIdTechnologiesGet(optId,params, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Update Technologies
 */
export const updateTechnologiesOptimizationOptIdTechnologiesPatch = (
    optId: number,
    updateTechnologiesOptimizationOptIdTechnologiesPatchBody: UpdateTechnologiesOptimizationOptIdTechnologiesPatchBody, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UpdateTechnologiesOptimizationOptIdTechnologiesPatch200>> => {
    return axios.patch(
      `/optimization/${optId}/technologies`,
      updateTechnologiesOptimizationOptIdTechnologiesPatchBody,options
    );
  }



export const getUpdateTechnologiesOptimizationOptIdTechnologiesPatchMutationFetcher = (optId: number, options?: AxiosRequestConfig) => {
  return (_: Key, { arg }: { arg: UpdateTechnologiesOptimizationOptIdTechnologiesPatchBody }) => {
    return updateTechnologiesOptimizationOptIdTechnologiesPatch(optId, arg, options);
  }
}
export const getUpdateTechnologiesOptimizationOptIdTechnologiesPatchMutationKey = (optId: number,) => [`/optimization/${optId}/technologies`] as const;

export type UpdateTechnologiesOptimizationOptIdTechnologiesPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateTechnologiesOptimizationOptIdTechnologiesPatch>>>
export type UpdateTechnologiesOptimizationOptIdTechnologiesPatchMutationError = AxiosError<HTTPValidationError>

/**
 * @summary Update Technologies
 */
export const useUpdateTechnologiesOptimizationOptIdTechnologiesPatch = <TError = AxiosError<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateTechnologiesOptimizationOptIdTechnologiesPatch>>, TError, Key, UpdateTechnologiesOptimizationOptIdTechnologiesPatchBody, Awaited<ReturnType<typeof updateTechnologiesOptimizationOptIdTechnologiesPatch>>> & { swrKey?: string }, axios?: AxiosRequestConfig}
) => {

  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateTechnologiesOptimizationOptIdTechnologiesPatchMutationKey(optId);
  const swrFn = getUpdateTechnologiesOptimizationOptIdTechnologiesPatchMutationFetcher(optId, axiosOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
