/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import useSWRMutation from 'swr/mutation';
import type {
  SWRMutationConfiguration
} from 'swr/mutation';

import type {
  GetTechnologiesOptimizationOptIdTechnologiesGet200,
  GetTechnologiesOptimizationOptIdTechnologiesGetParams,
  HTTPValidationError,
  UpdateTechnologiesOptimizationOptIdTechnologiesPatch200,
  UpdateTechnologiesOptimizationOptIdTechnologiesPatchBody
} from '.././model';



  
  
  
/**
 * @summary Get Technologies
 */
export type getTechnologiesOptimizationOptIdTechnologiesGetResponse200 = {
  data: GetTechnologiesOptimizationOptIdTechnologiesGet200
  status: 200
}

export type getTechnologiesOptimizationOptIdTechnologiesGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getTechnologiesOptimizationOptIdTechnologiesGetResponseSuccess = (getTechnologiesOptimizationOptIdTechnologiesGetResponse200) & {
  headers: Headers;
};
export type getTechnologiesOptimizationOptIdTechnologiesGetResponseError = (getTechnologiesOptimizationOptIdTechnologiesGetResponse422) & {
  headers: Headers;
};

export type getTechnologiesOptimizationOptIdTechnologiesGetResponse = (getTechnologiesOptimizationOptIdTechnologiesGetResponseSuccess | getTechnologiesOptimizationOptIdTechnologiesGetResponseError)

export const getGetTechnologiesOptimizationOptIdTechnologiesGetUrl = (optId: number,
    params?: GetTechnologiesOptimizationOptIdTechnologiesGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/optimization/${optId}/technologies?${stringifiedParams}` : `/optimization/${optId}/technologies`
}

export const getTechnologiesOptimizationOptIdTechnologiesGet = async (optId: number,
    params?: GetTechnologiesOptimizationOptIdTechnologiesGetParams, options?: RequestInit): Promise<getTechnologiesOptimizationOptIdTechnologiesGetResponse> => {
  
  const res = await fetch(getGetTechnologiesOptimizationOptIdTechnologiesGetUrl(optId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getTechnologiesOptimizationOptIdTechnologiesGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getTechnologiesOptimizationOptIdTechnologiesGetResponse
}




export const getGetTechnologiesOptimizationOptIdTechnologiesGetKey = (optId: number,
    params?: GetTechnologiesOptimizationOptIdTechnologiesGetParams,) => [`/optimization/${optId}/technologies`, ...(params ? [params]: [])] as const;

export type GetTechnologiesOptimizationOptIdTechnologiesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getTechnologiesOptimizationOptIdTechnologiesGet>>>
export type GetTechnologiesOptimizationOptIdTechnologiesGetQueryError = Promise<HTTPValidationError>

/**
 * @summary Get Technologies
 */
export const useGetTechnologiesOptimizationOptIdTechnologiesGet = <TError = Promise<HTTPValidationError>>(
  optId: number,
    params?: GetTechnologiesOptimizationOptIdTechnologiesGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getTechnologiesOptimizationOptIdTechnologiesGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(optId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetTechnologiesOptimizationOptIdTechnologiesGetKey(optId,params) : null);
  const swrFn = () => getTechnologiesOptimizationOptIdTechnologiesGet(optId,params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * @summary Update Technologies
 */
export type updateTechnologiesOptimizationOptIdTechnologiesPatchResponse200 = {
  data: UpdateTechnologiesOptimizationOptIdTechnologiesPatch200
  status: 200
}

export type updateTechnologiesOptimizationOptIdTechnologiesPatchResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type updateTechnologiesOptimizationOptIdTechnologiesPatchResponseSuccess = (updateTechnologiesOptimizationOptIdTechnologiesPatchResponse200) & {
  headers: Headers;
};
export type updateTechnologiesOptimizationOptIdTechnologiesPatchResponseError = (updateTechnologiesOptimizationOptIdTechnologiesPatchResponse422) & {
  headers: Headers;
};

export type updateTechnologiesOptimizationOptIdTechnologiesPatchResponse = (updateTechnologiesOptimizationOptIdTechnologiesPatchResponseSuccess | updateTechnologiesOptimizationOptIdTechnologiesPatchResponseError)

export const getUpdateTechnologiesOptimizationOptIdTechnologiesPatchUrl = (optId: number,) => {


  

  return `/optimization/${optId}/technologies`
}

export const updateTechnologiesOptimizationOptIdTechnologiesPatch = async (optId: number,
    updateTechnologiesOptimizationOptIdTechnologiesPatchBody: UpdateTechnologiesOptimizationOptIdTechnologiesPatchBody, options?: RequestInit): Promise<updateTechnologiesOptimizationOptIdTechnologiesPatchResponse> => {
  
  const res = await fetch(getUpdateTechnologiesOptimizationOptIdTechnologiesPatchUrl(optId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateTechnologiesOptimizationOptIdTechnologiesPatchBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: updateTechnologiesOptimizationOptIdTechnologiesPatchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateTechnologiesOptimizationOptIdTechnologiesPatchResponse
}




export const getUpdateTechnologiesOptimizationOptIdTechnologiesPatchMutationFetcher = (optId: number, options?: RequestInit) => {
  return (_: Key, { arg }: { arg: UpdateTechnologiesOptimizationOptIdTechnologiesPatchBody }) => {
    return updateTechnologiesOptimizationOptIdTechnologiesPatch(optId, arg, options);
  }
}
export const getUpdateTechnologiesOptimizationOptIdTechnologiesPatchMutationKey = (optId: number,) => [`/optimization/${optId}/technologies`] as const;

export type UpdateTechnologiesOptimizationOptIdTechnologiesPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateTechnologiesOptimizationOptIdTechnologiesPatch>>>
export type UpdateTechnologiesOptimizationOptIdTechnologiesPatchMutationError = Promise<HTTPValidationError>

/**
 * @summary Update Technologies
 */
export const useUpdateTechnologiesOptimizationOptIdTechnologiesPatch = <TError = Promise<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRMutationConfiguration<Awaited<ReturnType<typeof updateTechnologiesOptimizationOptIdTechnologiesPatch>>, TError, Key, UpdateTechnologiesOptimizationOptIdTechnologiesPatchBody, Awaited<ReturnType<typeof updateTechnologiesOptimizationOptIdTechnologiesPatch>>> & { swrKey?: string }, fetch?: RequestInit}
) => {

  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const swrKey = swrOptions?.swrKey ?? getUpdateTechnologiesOptimizationOptIdTechnologiesPatchMutationKey(optId);
  const swrFn = getUpdateTechnologiesOptimizationOptIdTechnologiesPatchMutationFetcher(optId, fetchOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
