/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import {
  Fuel
} from '.././model';
import type {
  GetTechnologiesOptimizationOptIdTechnologiesGet200,
  UpdateTechnologiesOptimizationOptIdTechnologiesPatch200
} from '.././model';


export const getGetTechnologiesOptimizationOptIdTechnologiesGetResponseMock = (): GetTechnologiesOptimizationOptIdTechnologiesGet200 => ({
        [faker.string.alphanumeric(5)]: {base_capacity: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), min_capacity: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), max_capacity: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), optimize: faker.datatype.boolean(), capex: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), opex: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), fuel_name: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.helpers.arrayElement(Object.values(Fuel)),null,]), undefined]), fuel_cost: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),null,]), undefined])}
      })

export const getUpdateTechnologiesOptimizationOptIdTechnologiesPatchResponseMock = (): UpdateTechnologiesOptimizationOptIdTechnologiesPatch200 => ({
        [faker.string.alphanumeric(5)]: {base_capacity: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), min_capacity: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), max_capacity: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), optimize: faker.datatype.boolean(), capex: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), opex: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), fuel_name: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.helpers.arrayElement(Object.values(Fuel)),null,]), undefined]), fuel_cost: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.number.float({min: undefined, max: undefined, fractionDigits: 2}),null,]), undefined])}
      })


export const getGetTechnologiesOptimizationOptIdTechnologiesGetMockHandler = (overrideResponse?: GetTechnologiesOptimizationOptIdTechnologiesGet200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetTechnologiesOptimizationOptIdTechnologiesGet200> | GetTechnologiesOptimizationOptIdTechnologiesGet200), options?: RequestHandlerOptions) => {
  return http.get('*/optimization/:optId/technologies', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetTechnologiesOptimizationOptIdTechnologiesGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getUpdateTechnologiesOptimizationOptIdTechnologiesPatchMockHandler = (overrideResponse?: UpdateTechnologiesOptimizationOptIdTechnologiesPatch200 | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<UpdateTechnologiesOptimizationOptIdTechnologiesPatch200> | UpdateTechnologiesOptimizationOptIdTechnologiesPatch200), options?: RequestHandlerOptions) => {
  return http.patch('*/optimization/:optId/technologies', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateTechnologiesOptimizationOptIdTechnologiesPatchResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}
export const getOptimizationTechnologyMock = () => [
  getGetTechnologiesOptimizationOptIdTechnologiesGetMockHandler(),
  getUpdateTechnologiesOptimizationOptIdTechnologiesPatchMockHandler()
]
