/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  OptConfig,
  OptimizationParamsResponse,
  ProfileDataResponse
} from '.././model';


export const getGetOptConfigOptimizationOptIdSummaryOptConfigGetResponseMock = (overrideResponse: Partial< OptConfig > = {}): OptConfig => ({ee_profile: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.float({min: undefined, max: undefined, fractionDigits: 2}))), pv_profile: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.float({min: undefined, max: undefined, fractionDigits: 2}))), temp_profile: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.float({min: undefined, max: undefined, fractionDigits: 2}))), base_heat_profile: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.float({min: undefined, max: undefined, fractionDigits: 2}))), opt_heat_profile: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.float({min: undefined, max: undefined, fractionDigits: 2}))), base_total_thermal_transmittance: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), base_total_foundation_transmittance: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), opt_total_thermal_transmittance: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), ventilation_heat_profile: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.number.float({min: undefined, max: undefined, fractionDigits: 2}))), day_hours: [], day_temp: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), night_temp: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), ...overrideResponse})

export const getGetOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetResponseMock = (overrideResponse: Partial< OptimizationParamsResponse > = {}): OptimizationParamsResponse => ({operator: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), tariff: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}),null,]), yearly_ee_demand: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), yearly_heat_demand: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), yearly_vent_heat_demand: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), yearly_opt_vent_heat_demand: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), yearly_opt_heat_demand: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), pv_potential: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), optimal_pv_azimuth: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), optimal_pv_slope: faker.number.float({min: undefined, max: undefined, fractionDigits: 2}), ...overrideResponse})

export const getGetProfileDataOptimizationOptIdSummaryProfileDataGetResponseMock = (overrideResponse: Partial< ProfileDataResponse > = {}): ProfileDataResponse => ({ee_profile: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), pv_profile: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), temp_profile: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), heat_profile: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({})), ...overrideResponse})


export const getGetOptConfigOptimizationOptIdSummaryOptConfigGetMockHandler = (overrideResponse?: OptConfig | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<OptConfig> | OptConfig), options?: RequestHandlerOptions) => {
  return http.get('*/optimization/:optId/summary/opt_config', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetOptConfigOptimizationOptIdSummaryOptConfigGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetMockHandler = (overrideResponse?: OptimizationParamsResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<OptimizationParamsResponse> | OptimizationParamsResponse), options?: RequestHandlerOptions) => {
  return http.get('*/optimization/:optId/summary/optimization_params', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetProfileDataOptimizationOptIdSummaryProfileDataGetMockHandler = (overrideResponse?: ProfileDataResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ProfileDataResponse> | ProfileDataResponse), options?: RequestHandlerOptions) => {
  return http.get('*/optimization/:optId/summary/profile_data', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetProfileDataOptimizationOptIdSummaryProfileDataGetResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  }, options)
}

export const getGetDemandXlsxOptimizationOptIdDemandXlsxGetMockHandler = (overrideResponse?: unknown | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<unknown> | unknown), options?: RequestHandlerOptions) => {
  return http.get('*/optimization/:optId/demand/xlsx', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  }, options)
}
export const getOptimizationSummaryMock = () => [
  getGetOptConfigOptimizationOptIdSummaryOptConfigGetMockHandler(),
  getGetOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetMockHandler(),
  getGetProfileDataOptimizationOptIdSummaryProfileDataGetMockHandler(),
  getGetDemandXlsxOptimizationOptIdDemandXlsxGetMockHandler()
]
