/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  GetOptConfigOptimizationOptIdSummaryOptConfigGetParams,
  HTTPValidationError,
  OptConfig,
  OptimizationParamsResponse,
  ProfileDataResponse
} from '.././model';



  
  
  
/**
 * Get optimization configuration
 * @summary Get Opt Config
 */
export type getOptConfigOptimizationOptIdSummaryOptConfigGetResponse200 = {
  data: OptConfig
  status: 200
}

export type getOptConfigOptimizationOptIdSummaryOptConfigGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getOptConfigOptimizationOptIdSummaryOptConfigGetResponseSuccess = (getOptConfigOptimizationOptIdSummaryOptConfigGetResponse200) & {
  headers: Headers;
};
export type getOptConfigOptimizationOptIdSummaryOptConfigGetResponseError = (getOptConfigOptimizationOptIdSummaryOptConfigGetResponse422) & {
  headers: Headers;
};

export type getOptConfigOptimizationOptIdSummaryOptConfigGetResponse = (getOptConfigOptimizationOptIdSummaryOptConfigGetResponseSuccess | getOptConfigOptimizationOptIdSummaryOptConfigGetResponseError)

export const getGetOptConfigOptimizationOptIdSummaryOptConfigGetUrl = (optId: number,
    params?: GetOptConfigOptimizationOptIdSummaryOptConfigGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/optimization/${optId}/summary/opt_config?${stringifiedParams}` : `/optimization/${optId}/summary/opt_config`
}

export const getOptConfigOptimizationOptIdSummaryOptConfigGet = async (optId: number,
    params?: GetOptConfigOptimizationOptIdSummaryOptConfigGetParams, options?: RequestInit): Promise<getOptConfigOptimizationOptIdSummaryOptConfigGetResponse> => {
  
  const res = await fetch(getGetOptConfigOptimizationOptIdSummaryOptConfigGetUrl(optId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getOptConfigOptimizationOptIdSummaryOptConfigGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getOptConfigOptimizationOptIdSummaryOptConfigGetResponse
}




export const getGetOptConfigOptimizationOptIdSummaryOptConfigGetKey = (optId: number,
    params?: GetOptConfigOptimizationOptIdSummaryOptConfigGetParams,) => [`/optimization/${optId}/summary/opt_config`, ...(params ? [params]: [])] as const;

export type GetOptConfigOptimizationOptIdSummaryOptConfigGetQueryResult = NonNullable<Awaited<ReturnType<typeof getOptConfigOptimizationOptIdSummaryOptConfigGet>>>
export type GetOptConfigOptimizationOptIdSummaryOptConfigGetQueryError = Promise<HTTPValidationError>

/**
 * @summary Get Opt Config
 */
export const useGetOptConfigOptimizationOptIdSummaryOptConfigGet = <TError = Promise<HTTPValidationError>>(
  optId: number,
    params?: GetOptConfigOptimizationOptIdSummaryOptConfigGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getOptConfigOptimizationOptIdSummaryOptConfigGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(optId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetOptConfigOptimizationOptIdSummaryOptConfigGetKey(optId,params) : null);
  const swrFn = () => getOptConfigOptimizationOptIdSummaryOptConfigGet(optId,params, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get optimization parameters
 * @summary Get Optimization Params
 */
export type getOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetResponse200 = {
  data: OptimizationParamsResponse
  status: 200
}

export type getOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetResponseSuccess = (getOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetResponse200) & {
  headers: Headers;
};
export type getOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetResponseError = (getOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetResponse422) & {
  headers: Headers;
};

export type getOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetResponse = (getOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetResponseSuccess | getOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetResponseError)

export const getGetOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetUrl = (optId: number,) => {


  

  return `/optimization/${optId}/summary/optimization_params`
}

export const getOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGet = async (optId: number, options?: RequestInit): Promise<getOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetResponse> => {
  
  const res = await fetch(getGetOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetUrl(optId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetResponse
}




export const getGetOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetKey = (optId: number,) => [`/optimization/${optId}/summary/optimization_params`] as const;

export type GetOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGet>>>
export type GetOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetQueryError = Promise<HTTPValidationError>

/**
 * @summary Get Optimization Params
 */
export const useGetOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGet = <TError = Promise<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(optId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetKey(optId) : null);
  const swrFn = () => getOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGet(optId, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get optimization profile data
 * @summary Get Profile Data
 */
export type getProfileDataOptimizationOptIdSummaryProfileDataGetResponse200 = {
  data: ProfileDataResponse
  status: 200
}

export type getProfileDataOptimizationOptIdSummaryProfileDataGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getProfileDataOptimizationOptIdSummaryProfileDataGetResponseSuccess = (getProfileDataOptimizationOptIdSummaryProfileDataGetResponse200) & {
  headers: Headers;
};
export type getProfileDataOptimizationOptIdSummaryProfileDataGetResponseError = (getProfileDataOptimizationOptIdSummaryProfileDataGetResponse422) & {
  headers: Headers;
};

export type getProfileDataOptimizationOptIdSummaryProfileDataGetResponse = (getProfileDataOptimizationOptIdSummaryProfileDataGetResponseSuccess | getProfileDataOptimizationOptIdSummaryProfileDataGetResponseError)

export const getGetProfileDataOptimizationOptIdSummaryProfileDataGetUrl = (optId: number,) => {


  

  return `/optimization/${optId}/summary/profile_data`
}

export const getProfileDataOptimizationOptIdSummaryProfileDataGet = async (optId: number, options?: RequestInit): Promise<getProfileDataOptimizationOptIdSummaryProfileDataGetResponse> => {
  
  const res = await fetch(getGetProfileDataOptimizationOptIdSummaryProfileDataGetUrl(optId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getProfileDataOptimizationOptIdSummaryProfileDataGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getProfileDataOptimizationOptIdSummaryProfileDataGetResponse
}




export const getGetProfileDataOptimizationOptIdSummaryProfileDataGetKey = (optId: number,) => [`/optimization/${optId}/summary/profile_data`] as const;

export type GetProfileDataOptimizationOptIdSummaryProfileDataGetQueryResult = NonNullable<Awaited<ReturnType<typeof getProfileDataOptimizationOptIdSummaryProfileDataGet>>>
export type GetProfileDataOptimizationOptIdSummaryProfileDataGetQueryError = Promise<HTTPValidationError>

/**
 * @summary Get Profile Data
 */
export const useGetProfileDataOptimizationOptIdSummaryProfileDataGet = <TError = Promise<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getProfileDataOptimizationOptIdSummaryProfileDataGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(optId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetProfileDataOptimizationOptIdSummaryProfileDataGetKey(optId) : null);
  const swrFn = () => getProfileDataOptimizationOptIdSummaryProfileDataGet(optId, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get demand data in xlsx format
 * @summary Get Demand Xlsx
 */
export type getDemandXlsxOptimizationOptIdDemandXlsxGetResponse200 = {
  data: unknown
  status: 200
}

export type getDemandXlsxOptimizationOptIdDemandXlsxGetResponse422 = {
  data: HTTPValidationError
  status: 422
}
    
export type getDemandXlsxOptimizationOptIdDemandXlsxGetResponseSuccess = (getDemandXlsxOptimizationOptIdDemandXlsxGetResponse200) & {
  headers: Headers;
};
export type getDemandXlsxOptimizationOptIdDemandXlsxGetResponseError = (getDemandXlsxOptimizationOptIdDemandXlsxGetResponse422) & {
  headers: Headers;
};

export type getDemandXlsxOptimizationOptIdDemandXlsxGetResponse = (getDemandXlsxOptimizationOptIdDemandXlsxGetResponseSuccess | getDemandXlsxOptimizationOptIdDemandXlsxGetResponseError)

export const getGetDemandXlsxOptimizationOptIdDemandXlsxGetUrl = (optId: number,) => {


  

  return `/optimization/${optId}/demand/xlsx`
}

export const getDemandXlsxOptimizationOptIdDemandXlsxGet = async (optId: number, options?: RequestInit): Promise<getDemandXlsxOptimizationOptIdDemandXlsxGetResponse> => {
  
  const res = await fetch(getGetDemandXlsxOptimizationOptIdDemandXlsxGetUrl(optId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getDemandXlsxOptimizationOptIdDemandXlsxGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getDemandXlsxOptimizationOptIdDemandXlsxGetResponse
}




export const getGetDemandXlsxOptimizationOptIdDemandXlsxGetKey = (optId: number,) => [`/optimization/${optId}/demand/xlsx`] as const;

export type GetDemandXlsxOptimizationOptIdDemandXlsxGetQueryResult = NonNullable<Awaited<ReturnType<typeof getDemandXlsxOptimizationOptIdDemandXlsxGet>>>
export type GetDemandXlsxOptimizationOptIdDemandXlsxGetQueryError = Promise<HTTPValidationError>

/**
 * @summary Get Demand Xlsx
 */
export const useGetDemandXlsxOptimizationOptIdDemandXlsxGet = <TError = Promise<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getDemandXlsxOptimizationOptIdDemandXlsxGet>>, TError> & { swrKey?: Key, enabled?: boolean }, fetch?: RequestInit }
) => {
  const {swr: swrOptions, fetch: fetchOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(optId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetDemandXlsxOptimizationOptIdDemandXlsxGetKey(optId) : null);
  const swrFn = () => getDemandXlsxOptimizationOptIdDemandXlsxGet(optId, fetchOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
