/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import useSwr from 'swr';
import type {
  Key,
  SWRConfiguration
} from 'swr';

import type {
  GetOptConfigOptimizationOptIdSummaryOptConfigGetParams,
  HTTPValidationError,
  OptConfig,
  OptimizationParamsResponse,
  ProfileDataResponse
} from '.././model';



  
  
  
/**
 * Get optimization configuration
 * @summary Get Opt Config
 */
export const getOptConfigOptimizationOptIdSummaryOptConfigGet = (
    optId: number,
    params?: GetOptConfigOptimizationOptIdSummaryOptConfigGetParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OptConfig>> => {
    return axios.get(
      `/optimization/${optId}/summary/opt_config`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getGetOptConfigOptimizationOptIdSummaryOptConfigGetKey = (optId: number,
    params?: GetOptConfigOptimizationOptIdSummaryOptConfigGetParams,) => [`/optimization/${optId}/summary/opt_config`, ...(params ? [params]: [])] as const;

export type GetOptConfigOptimizationOptIdSummaryOptConfigGetQueryResult = NonNullable<Awaited<ReturnType<typeof getOptConfigOptimizationOptIdSummaryOptConfigGet>>>
export type GetOptConfigOptimizationOptIdSummaryOptConfigGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get Opt Config
 */
export const useGetOptConfigOptimizationOptIdSummaryOptConfigGet = <TError = AxiosError<HTTPValidationError>>(
  optId: number,
    params?: GetOptConfigOptimizationOptIdSummaryOptConfigGetParams, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getOptConfigOptimizationOptIdSummaryOptConfigGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(optId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetOptConfigOptimizationOptIdSummaryOptConfigGetKey(optId,params) : null);
  const swrFn = () => getOptConfigOptimizationOptIdSummaryOptConfigGet(optId,params, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get optimization parameters
 * @summary Get Optimization Params
 */
export const getOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGet = (
    optId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OptimizationParamsResponse>> => {
    return axios.get(
      `/optimization/${optId}/summary/optimization_params`,options
    );
  }



export const getGetOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetKey = (optId: number,) => [`/optimization/${optId}/summary/optimization_params`] as const;

export type GetOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGet>>>
export type GetOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get Optimization Params
 */
export const useGetOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGet = <TError = AxiosError<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(optId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGetKey(optId) : null);
  const swrFn = () => getOptimizationParamsOptimizationOptIdSummaryOptimizationParamsGet(optId, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get optimization profile data
 * @summary Get Profile Data
 */
export const getProfileDataOptimizationOptIdSummaryProfileDataGet = (
    optId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProfileDataResponse>> => {
    return axios.get(
      `/optimization/${optId}/summary/profile_data`,options
    );
  }



export const getGetProfileDataOptimizationOptIdSummaryProfileDataGetKey = (optId: number,) => [`/optimization/${optId}/summary/profile_data`] as const;

export type GetProfileDataOptimizationOptIdSummaryProfileDataGetQueryResult = NonNullable<Awaited<ReturnType<typeof getProfileDataOptimizationOptIdSummaryProfileDataGet>>>
export type GetProfileDataOptimizationOptIdSummaryProfileDataGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get Profile Data
 */
export const useGetProfileDataOptimizationOptIdSummaryProfileDataGet = <TError = AxiosError<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getProfileDataOptimizationOptIdSummaryProfileDataGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(optId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetProfileDataOptimizationOptIdSummaryProfileDataGetKey(optId) : null);
  const swrFn = () => getProfileDataOptimizationOptIdSummaryProfileDataGet(optId, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
/**
 * Get demand data in xlsx format
 * @summary Get Demand Xlsx
 */
export const getDemandXlsxOptimizationOptIdDemandXlsxGet = (
    optId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    return axios.get(
      `/optimization/${optId}/demand/xlsx`,options
    );
  }



export const getGetDemandXlsxOptimizationOptIdDemandXlsxGetKey = (optId: number,) => [`/optimization/${optId}/demand/xlsx`] as const;

export type GetDemandXlsxOptimizationOptIdDemandXlsxGetQueryResult = NonNullable<Awaited<ReturnType<typeof getDemandXlsxOptimizationOptIdDemandXlsxGet>>>
export type GetDemandXlsxOptimizationOptIdDemandXlsxGetQueryError = AxiosError<HTTPValidationError>

/**
 * @summary Get Demand Xlsx
 */
export const useGetDemandXlsxOptimizationOptIdDemandXlsxGet = <TError = AxiosError<HTTPValidationError>>(
  optId: number, options?: { swr?:SWRConfiguration<Awaited<ReturnType<typeof getDemandXlsxOptimizationOptIdDemandXlsxGet>>, TError> & { swrKey?: Key, enabled?: boolean }, axios?: AxiosRequestConfig }
) => {
  const {swr: swrOptions, axios: axiosOptions} = options ?? {}

  const isEnabled = swrOptions?.enabled !== false && !!(optId)
  const swrKey = swrOptions?.swrKey ?? (() => isEnabled ? getGetDemandXlsxOptimizationOptIdDemandXlsxGetKey(optId) : null);
  const swrFn = () => getDemandXlsxOptimizationOptIdDemandXlsxGet(optId, axiosOptions)

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(swrKey, swrFn, swrOptions)

  return {
    swrKey,
    ...query
  }
}
